[Uno.Compiler.UxGenerated]
public partial class InputPage: Fuse.Controls.Page
{
    [Uno.Compiler.UxGenerated]
    public partial class Template: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly InputPage __parent;
        [Uno.WeakReference] internal readonly InputPage __parentInstance;
        public Template(InputPage parent, InputPage parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        global::Uno.UX.Property<string> __self_Text_inst;
        internal global::Fuse.Reactive.EventBinding temp_eb11;
        static Template()
        {
        }
        public override object New()
        {
            var __self = new global::wbButton();
            __self_Text_inst = new AccountBook_FuseControlsButtonBase_Text_Property(__self, __selector0);
            var temp = new global::Fuse.Reactive.Data("");
            var temp1 = new global::Fuse.Reactive.Data("BalanceAdd");
            var temp2 = new global::Fuse.Reactive.DataBinding(__self_Text_inst, temp, Fuse.Reactive.BindingMode.Default);
            temp_eb11 = new global::Fuse.Reactive.EventBinding(temp1);
            __self.SourceLineNumber = 45;
            __self.SourceFileName = "InputPage.ux";
            global::Fuse.Gestures.Clicked.AddHandler(__self, temp_eb11.OnEvent);
            temp.SourceLineNumber = 45;
            temp.SourceFileName = "InputPage.ux";
            temp1.SourceLineNumber = 45;
            temp1.SourceFileName = "InputPage.ux";
            __self.Bindings.Add(temp2);
            __self.Bindings.Add(temp_eb11);
            return __self;
        }
        static global::Uno.UX.Selector __selector0 = "Text";
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template1: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly InputPage __parent;
        [Uno.WeakReference] internal readonly InputPage __parentInstance;
        public Template1(InputPage parent, InputPage parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        global::Uno.UX.Property<bool> ModalConfirm_IsEnabled_inst;
        global::Uno.UX.Property<string> temp_Text_inst;
        internal global::Fuse.Reactive.EventBinding temp_eb15;
        internal global::Fuse.Reactive.EventBinding temp_eb16;
        static Template1()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Controls.Grid();
            ModalConfirm_IsEnabled_inst = new AccountBook_FuseAlternateRoot_IsEnabled_Property(__parent.ModalConfirm, __selector0);
            var temp1 = new global::Fuse.Reactive.Data("SelectUsage");
            var temp = new global::wbButton_Left();
            temp_Text_inst = new AccountBook_FuseControlsButtonBase_Text_Property(temp, __selector1);
            var temp2 = new global::Fuse.Reactive.Data("name");
            var temp3 = new global::Fuse.Reactive.Data("removeItem");
            var temp4 = new global::Fuse.Controls.ScrollView();
            var temp5 = new global::Fuse.Gestures.Clicked();
            var temp6 = new global::Fuse.Triggers.Actions.Set<bool>(ModalConfirm_IsEnabled_inst);
            var temp7 = new global::Fuse.PlaySound();
            temp_eb15 = new global::Fuse.Reactive.EventBinding(temp1);
            var temp8 = new global::Fuse.Reactive.DataBinding(temp_Text_inst, temp2, Fuse.Reactive.BindingMode.Default);
            var temp9 = new global::wbButton();
            temp_eb16 = new global::Fuse.Reactive.EventBinding(temp3);
            var temp10 = new global::Fuse.Triggers.LayoutAnimation();
            var temp11 = new global::Fuse.Animations.Move();
            var temp12 = new global::Fuse.Triggers.AddingAnimation();
            var temp13 = new global::Fuse.Animations.Move();
            var temp14 = new global::Fuse.Triggers.RemovingAnimation();
            var temp15 = new global::Fuse.Animations.Move();
            __self.ColumnCount = 10;
            __self.SourceLineNumber = 79;
            __self.SourceFileName = "InputPage.ux";
            temp4.AllowedScrollDirections = Fuse.Controls.ScrollDirections.Horizontal;
            temp4.SourceLineNumber = 80;
            temp4.SourceFileName = "InputPage.ux";
            global::Fuse.Controls.Grid.SetColumnSpan(temp4, 7);
            temp4.Children.Add(temp);
            temp.SourceLineNumber = 81;
            temp.SourceFileName = "InputPage.ux";
            global::Fuse.Gestures.Clicked.AddHandler(temp, temp_eb15.OnEvent);
            temp.Children.Add(temp5);
            temp.Bindings.Add(temp_eb15);
            temp.Bindings.Add(temp8);
            temp5.SourceLineNumber = 82;
            temp5.SourceFileName = "InputPage.ux";
            temp5.Actions.Add(temp6);
            temp5.Actions.Add(temp7);
            temp6.Value = false;
            temp6.SourceLineNumber = 83;
            temp6.SourceFileName = "InputPage.ux";
            temp7.SourceLineNumber = 84;
            temp7.SourceFileName = "InputPage.ux";
            temp7.File = new global::Uno.UX.BundleFileSource(import("../../Click.wav"));
            temp1.SourceLineNumber = 81;
            temp1.SourceFileName = "InputPage.ux";
            temp2.SourceLineNumber = 81;
            temp2.SourceFileName = "InputPage.ux";
            temp9.Text = "Delete";
            temp9.Margin = float4(7f, 7f, 7f, 7f);
            temp9.SourceLineNumber = 88;
            temp9.SourceFileName = "InputPage.ux";
            global::Fuse.Controls.Grid.SetColumnSpan(temp9, 3);
            global::Fuse.Gestures.Clicked.AddHandler(temp9, temp_eb16.OnEvent);
            temp9.Bindings.Add(temp_eb16);
            temp3.SourceLineNumber = 88;
            temp3.SourceFileName = "InputPage.ux";
            temp10.SourceLineNumber = 89;
            temp10.SourceFileName = "InputPage.ux";
            temp10.Animators.Add(temp11);
            temp11.Y = 1f;
            temp11.Duration = 0.4;
            temp11.RelativeTo = Fuse.Triggers.LayoutTransition.PositionLayoutChange;
            temp11.Easing = Fuse.Animations.Easing.ElasticIn;
            temp12.SourceLineNumber = 93;
            temp12.SourceFileName = "InputPage.ux";
            temp12.Animators.Add(temp13);
            temp13.X = 1f;
            temp13.Duration = 0.3;
            temp13.RelativeTo = Fuse.TranslationModes.Size;
            temp13.Easing = Fuse.Animations.Easing.CircularIn;
            temp14.SourceLineNumber = 97;
            temp14.SourceFileName = "InputPage.ux";
            temp14.Animators.Add(temp15);
            temp15.X = -1f;
            temp15.Duration = 0.4;
            temp15.RelativeTo = Fuse.TranslationModes.Size;
            temp15.Easing = Fuse.Animations.Easing.CircularOut;
            __self.Children.Add(temp4);
            __self.Children.Add(temp9);
            __self.Children.Add(temp10);
            __self.Children.Add(temp12);
            __self.Children.Add(temp14);
            return __self;
        }
        static global::Uno.UX.Selector __selector0 = "IsEnabled";
        static global::Uno.UX.Selector __selector1 = "Text";
    }
    global::Uno.UX.Property<string> temp_Value_inst;
    global::Uno.UX.Property<string> temp1_Value_inst;
    global::Uno.UX.Property<float4> temp2_TextColor_inst;
    global::Uno.UX.Property<string> temp2_Value_inst;
    global::Uno.UX.Property<float4> temp3_Color_inst;
    global::Uno.UX.Property<float> ScreenGrid_Opacity_inst;
    global::Uno.UX.Property<string> usageTextInput_Value_inst;
    global::Uno.UX.Property<string> temp4_Text_inst;
    global::Uno.UX.Property<bool> ModalConfirm_IsEnabled_inst;
    global::Uno.UX.Property<object> temp5_Items_inst;
    global::Uno.UX.Property<string> temp6_Text_inst;
    global::Uno.UX.Property<float4> KeyboardGrid_Color_inst;
    global::Uno.UX.Property<float4> temp7_Color_inst;
    global::Uno.UX.Property<string> popup_input_Value_inst;
    global::Uno.UX.Property<float4> temp8_Color_inst;
    global::Uno.UX.Property<object> temp9_Items_inst;
    global::Uno.UX.Property<int> temp9_Offset_inst;
    global::Uno.UX.Property<int> temp9_Limit_inst;
    global::Uno.UX.Property<float4> temp10_Color_inst;
    global::Uno.UX.Property<Fuse.Visual> ModalConfirm_ParentNode_inst;
    internal global::Fuse.Controls.Panel FullWindo;
    internal global::Fuse.Controls.Grid ScreenGrid;
    internal global::Fuse.Controls.Grid KeyboardGrid;
    internal global::Fuse.Controls.TextInput usageTextInput;
    internal global::Fuse.Reactive.EventBinding temp_eb10;
    internal global::wbButton usage_button;
    internal global::Fuse.Reactive.EventBinding temp_eb12;
    internal global::Fuse.Reactive.EventBinding temp_eb13;
    internal global::Fuse.AlternateRoot ModalConfirm;
    internal global::Fuse.Controls.TextInput popup_input;
    internal global::Fuse.Reactive.EventBinding temp_eb14;
    global::Uno.UX.NameTable __g_nametable;
    static string[] __g_static_nametable = new string[] {
        "FullWindo",
        "ScreenGrid",
        "KeyboardGrid",
        "usageTextInput",
        "temp_eb10",
        "usage_button",
        "temp_eb12",
        "temp_eb13",
        "ModalConfirm",
        "popup_input",
        "temp_eb14"
    };
    static InputPage()
    {
    }
    [global::Uno.UX.UXConstructor]
    public InputPage()
    {
        InitializeUX();
    }
    void InitializeUX()
    {
        __g_nametable = new global::Uno.UX.NameTable(null, __g_static_nametable);
        var temp = new global::Fuse.Controls.Text();
        temp_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp, __selector0);
        var temp11 = new global::Fuse.Reactive.Data("cashOrCardText");
        var temp1 = new global::Fuse.Controls.Text();
        temp1_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp1, __selector0);
        var temp12 = new global::Fuse.Reactive.Data("currentBalance");
        var temp2 = new global::Fuse.Controls.Text();
        temp2_TextColor_inst = new AccountBook_FuseControlsTextControl_TextColor_Property(temp2, __selector1);
        var temp13 = new global::Fuse.Reactive.Data("addingValueColor");
        var temp14 = new global::Fuse.Reactive.Data("inputVars");
        var temp15 = new global::Fuse.Reactive.Member(temp14, "pmType");
        var temp16 = " ";
        var temp17 = new global::Fuse.Reactive.Constant(temp16);
        var temp18 = new global::Fuse.Reactive.Data("addingValue");
        var temp19 = new global::Fuse.Reactive.Add(temp17, temp18);
        temp2_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp2, __selector0);
        var temp20 = new global::Fuse.Reactive.Add(temp15, temp19);
        var temp3 = new global::Fuse.Controls.Rectangle();
        temp3_Color_inst = new AccountBook_FuseControlsShape_Color_Property(temp3, __selector2);
        var temp21 = new global::Fuse.Reactive.Resource("Col_type3");
        ScreenGrid = new global::Fuse.Controls.Grid();
        ScreenGrid_Opacity_inst = new AccountBook_FuseElementsElement_Opacity_Property(ScreenGrid, __selector3);
        var temp22 = new global::Fuse.Reactive.Data("inputVars");
        usageTextInput = new global::Fuse.Controls.TextInput();
        usageTextInput_Value_inst = new AccountBook_FuseControlsTextInputControl_Value_Property(usageTextInput, __selector0);
        var temp23 = new global::Fuse.Reactive.Member(temp22, "usage");
        var temp4 = new global::wbButton();
        temp4_Text_inst = new AccountBook_FuseControlsButtonBase_Text_Property(temp4, __selector4);
        var temp24 = new global::Fuse.Reactive.Data("payTypeText");
        var temp25 = new global::Fuse.Reactive.Data("PayTypeChange");
        ModalConfirm = new global::Fuse.AlternateRoot();
        ModalConfirm_IsEnabled_inst = new AccountBook_FuseAlternateRoot_IsEnabled_Property(ModalConfirm, __selector5);
        var temp5 = new global::Fuse.Reactive.Each();
        temp5_Items_inst = new AccountBook_FuseReactiveEach_Items_Property(temp5, __selector6);
        var temp26 = new global::Fuse.Reactive.Data("numSet");
        var temp27 = new global::Fuse.Reactive.Data("Backspace");
        var temp6 = new global::pmButton();
        temp6_Text_inst = new AccountBook_pmButton_Text_Property(temp6, __selector4);
        var temp28 = new global::Fuse.Reactive.Data("pmTypeText");
        var temp29 = new global::Fuse.Reactive.Data("Submit");
        KeyboardGrid = new global::Fuse.Controls.Grid();
        KeyboardGrid_Color_inst = new AccountBook_FuseControlsPanel_Color_Property(KeyboardGrid, __selector2);
        var temp30 = new global::Fuse.Reactive.Resource("Col_type3");
        var temp7 = new global::Fuse.Drawing.Stroke();
        temp7_Color_inst = new AccountBook_FuseDrawingStroke_Color_Property(temp7, __selector2);
        var temp31 = new global::Fuse.Reactive.Resource("Col_type3");
        popup_input = new global::Fuse.Controls.TextInput();
        popup_input_Value_inst = new AccountBook_FuseControlsTextInputControl_Value_Property(popup_input, __selector0);
        var temp32 = new global::Fuse.Reactive.Data("usageListAddInput");
        var temp33 = new global::Fuse.Reactive.Data("AddToTempUsageList");
        var temp8 = new global::Fuse.Controls.Rectangle();
        temp8_Color_inst = new AccountBook_FuseControlsShape_Color_Property(temp8, __selector2);
        var temp34 = new global::Fuse.Reactive.Resource("Col_type3");
        var temp9 = new global::Fuse.Reactive.Each();
        temp9_Items_inst = new AccountBook_FuseReactiveEach_Items_Property(temp9, __selector6);
        var temp35 = new global::Fuse.Reactive.Data("tempUsageList");
        temp9_Offset_inst = new AccountBook_FuseReactiveEach_Offset_Property(temp9, __selector7);
        var temp36 = new global::Fuse.Reactive.Data("offset");
        temp9_Limit_inst = new AccountBook_FuseReactiveEach_Limit_Property(temp9, __selector8);
        var temp37 = new global::Fuse.Reactive.Data("limit");
        var temp10 = new global::Fuse.Drawing.Stroke();
        temp10_Color_inst = new AccountBook_FuseDrawingStroke_Color_Property(temp10, __selector2);
        var temp38 = new global::Fuse.Reactive.Resource("Col_type3");
        ModalConfirm_ParentNode_inst = new AccountBook_FuseAlternateRoot_ParentNode_Property(ModalConfirm, __selector9);
        var temp39 = new global::Fuse.Reactive.Resource("FullWindow");
        var temp40 = new global::Fuse.Reactive.JavaScript(__g_nametable);
        FullWindo = new global::Fuse.Controls.Panel();
        var temp41 = new global::Fuse.Controls.Grid();
        var temp42 = new global::Fuse.Controls.DockPanel();
        var temp43 = new global::Fuse.Controls.Panel();
        var temp44 = new global::Fuse.Controls.Panel();
        var temp45 = new global::Fuse.Controls.Rectangle();
        var temp46 = new global::Fuse.Reactive.DataBinding(temp_Value_inst, temp11, Fuse.Reactive.BindingMode.Default);
        var temp47 = new global::Fuse.Controls.Text();
        var temp48 = new global::Fuse.Reactive.DataBinding(temp1_Value_inst, temp12, Fuse.Reactive.BindingMode.Default);
        var temp49 = new global::Fuse.Reactive.DataBinding(temp2_TextColor_inst, temp13, Fuse.Reactive.BindingMode.Default);
        var temp50 = new global::Fuse.Reactive.DataBinding(temp2_Value_inst, temp20, Fuse.Reactive.BindingMode.Default);
        var temp51 = new global::Fuse.Controls.Panel();
        var temp52 = new global::Fuse.Controls.Panel();
        var temp53 = new global::Fuse.Reactive.DataBinding(temp3_Color_inst, temp21, Fuse.Reactive.BindingMode.Default);
        var temp54 = new global::Fuse.Triggers.WhileKeyboardVisible();
        var temp55 = new global::Fuse.Animations.Change<float>(ScreenGrid_Opacity_inst);
        var temp56 = new global::Fuse.Controls.DockPanel();
        var temp57 = new global::Fuse.Controls.Rectangle();
        var temp58 = new global::Fuse.Drawing.SolidColor();
        var temp59 = new global::Fuse.Drawing.Stroke();
        var temp60 = new global::Fuse.Reactive.DataBinding(usageTextInput_Value_inst, temp23, Fuse.Reactive.BindingMode.Default);
        var temp61 = new global::Fuse.Reactive.DataBinding(temp4_Text_inst, temp24, Fuse.Reactive.BindingMode.Default);
        temp_eb10 = new global::Fuse.Reactive.EventBinding(temp25);
        var temp62 = new global::Fuse.Controls.Grid();
        usage_button = new global::wbButton();
        var temp63 = new global::Fuse.Gestures.Clicked();
        var temp64 = new global::Fuse.Triggers.Actions.Set<bool>(ModalConfirm_IsEnabled_inst);
        var temp65 = new Template(this, this);
        var temp66 = new global::Fuse.Reactive.DataBinding(temp5_Items_inst, temp26, Fuse.Reactive.BindingMode.Default);
        var temp67 = new global::wbButton();
        temp_eb12 = new global::Fuse.Reactive.EventBinding(temp27);
        var temp68 = new global::Fuse.Reactive.DataBinding(temp6_Text_inst, temp28, Fuse.Reactive.BindingMode.Default);
        var temp69 = new global::wbButton();
        temp_eb13 = new global::Fuse.Reactive.EventBinding(temp29);
        var temp70 = new global::Fuse.Triggers.WhileKeyboardVisible();
        var temp71 = new global::Fuse.Animations.Move();
        var temp72 = new global::Fuse.Reactive.DataBinding(KeyboardGrid_Color_inst, temp30, Fuse.Reactive.BindingMode.Default);
        var temp73 = new global::Fuse.Resources.ResourceObject();
        var temp74 = new global::Fuse.Controls.Panel();
        var temp75 = new global::Fuse.Controls.StackPanel();
        var temp76 = new global::Fuse.Controls.Rectangle();
        var temp77 = new global::Fuse.Reactive.DataBinding(temp7_Color_inst, temp31, Fuse.Reactive.BindingMode.Default);
        var temp78 = new global::Fuse.Controls.ScrollView();
        var temp79 = new global::Fuse.Controls.Grid();
        var temp80 = new global::Fuse.Reactive.DataBinding(popup_input_Value_inst, temp32, Fuse.Reactive.BindingMode.Default);
        var temp81 = new global::wbButton();
        temp_eb14 = new global::Fuse.Reactive.EventBinding(temp33);
        var temp82 = new global::Fuse.Reactive.DataBinding(temp8_Color_inst, temp34, Fuse.Reactive.BindingMode.Default);
        var temp83 = new global::Fuse.Controls.DockPanel();
        var temp84 = new global::Fuse.Controls.ScrollView();
        var temp85 = new global::Fuse.Controls.StackPanel();
        var temp86 = new Template1(this, this);
        var temp87 = new global::Fuse.Reactive.DataBinding(temp9_Items_inst, temp35, Fuse.Reactive.BindingMode.Default);
        var temp88 = new global::Fuse.Reactive.DataBinding(temp9_Offset_inst, temp36, Fuse.Reactive.BindingMode.Default);
        var temp89 = new global::Fuse.Reactive.DataBinding(temp9_Limit_inst, temp37, Fuse.Reactive.BindingMode.Default);
        var temp90 = new global::Fuse.Controls.Button();
        var temp91 = new global::Fuse.Controls.Text();
        var temp92 = new global::Fuse.Controls.Rectangle();
        var temp93 = new global::Fuse.Reactive.DataBinding(temp10_Color_inst, temp38, Fuse.Reactive.BindingMode.Default);
        var temp94 = new global::Fuse.Gestures.Clicked();
        var temp95 = new global::Fuse.Triggers.Actions.Set<bool>(ModalConfirm_IsEnabled_inst);
        var temp96 = new global::Fuse.PlaySound();
        var temp97 = new global::Fuse.Reactive.DataBinding(ModalConfirm_ParentNode_inst, temp39, Fuse.Reactive.BindingMode.Default);
        this.SourceLineNumber = 1;
        this.SourceFileName = "InputPage.ux";
        temp40.LineNumber = 2;
        temp40.FileName = "InputPage.ux";
        temp40.SourceLineNumber = 2;
        temp40.SourceFileName = "InputPage.ux";
        temp40.File = new global::Uno.UX.BundleFileSource(import("../../Modules/InputPage.js"));
        FullWindo.Layer = Fuse.Layer.Overlay;
        FullWindo.Name = __selector10;
        FullWindo.SourceLineNumber = 3;
        FullWindo.SourceFileName = "InputPage.ux";
        temp41.RowCount = 100;
        temp41.SourceLineNumber = 4;
        temp41.SourceFileName = "InputPage.ux";
        temp41.Children.Add(temp42);
        temp41.Children.Add(temp56);
        temp42.SourceLineNumber = 5;
        temp42.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp42, 57);
        temp42.Children.Add(ScreenGrid);
        temp42.Children.Add(temp54);
        ScreenGrid.RowCount = 57;
        ScreenGrid.Name = __selector11;
        ScreenGrid.SourceLineNumber = 6;
        ScreenGrid.SourceFileName = "InputPage.ux";
        ScreenGrid.Children.Add(temp43);
        ScreenGrid.Children.Add(temp44);
        ScreenGrid.Children.Add(temp);
        ScreenGrid.Children.Add(temp47);
        ScreenGrid.Children.Add(temp1);
        ScreenGrid.Children.Add(temp2);
        ScreenGrid.Children.Add(temp51);
        ScreenGrid.Children.Add(temp52);
        temp43.SourceLineNumber = 7;
        temp43.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp43, 21);
        temp44.SourceLineNumber = 8;
        temp44.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp44, 3);
        temp44.Children.Add(temp45);
        temp45.Color = float4(1f, 1f, 1f, 1f);
        temp45.SourceLineNumber = 9;
        temp45.SourceFileName = "InputPage.ux";
        temp.Color = float4(0f, 0f, 0f, 1f);
        temp.Alignment = Fuse.Elements.Alignment.Center;
        temp.SourceLineNumber = 12;
        temp.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp, 3);
        temp.Bindings.Add(temp46);
        temp11.SourceLineNumber = 12;
        temp11.SourceFileName = "InputPage.ux";
        temp47.Value = "Current Balance";
        temp47.Color = float4(0f, 0f, 0f, 1f);
        temp47.Alignment = Fuse.Elements.Alignment.Center;
        temp47.SourceLineNumber = 13;
        temp47.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp47, 3);
        temp1.FontSize = 45f;
        temp1.Color = float4(0f, 0f, 0f, 1f);
        temp1.Alignment = Fuse.Elements.Alignment.Center;
        temp1.SourceLineNumber = 14;
        temp1.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp1, 7);
        temp1.Bindings.Add(temp48);
        temp12.SourceLineNumber = 14;
        temp12.SourceFileName = "InputPage.ux";
        temp2.FontSize = 30f;
        temp2.Alignment = Fuse.Elements.Alignment.Center;
        temp2.SourceLineNumber = 15;
        temp2.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp2, 2);
        temp2.Bindings.Add(temp49);
        temp2.Bindings.Add(temp50);
        temp13.SourceLineNumber = 15;
        temp13.SourceFileName = "InputPage.ux";
        temp20.SourceLineNumber = 15;
        temp20.SourceFileName = "InputPage.ux";
        temp14.SourceLineNumber = 15;
        temp14.SourceFileName = "InputPage.ux";
        temp15.SourceLineNumber = 15;
        temp15.SourceFileName = "InputPage.ux";
        temp19.SourceLineNumber = 15;
        temp19.SourceFileName = "InputPage.ux";
        temp17.SourceLineNumber = 15;
        temp17.SourceFileName = "InputPage.ux";
        temp18.SourceLineNumber = 15;
        temp18.SourceFileName = "InputPage.ux";
        temp51.SourceLineNumber = 16;
        temp51.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp51, 15);
        temp52.SourceLineNumber = 17;
        temp52.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp52, 3);
        temp52.Children.Add(temp3);
        temp3.SourceLineNumber = 18;
        temp3.SourceFileName = "InputPage.ux";
        temp3.Bindings.Add(temp53);
        temp21.SourceLineNumber = 18;
        temp21.SourceFileName = "InputPage.ux";
        temp54.SourceLineNumber = 22;
        temp54.SourceFileName = "InputPage.ux";
        temp54.Animators.Add(temp55);
        temp55.Value = 0f;
        temp55.Duration = 0.3;
        temp56.SourceLineNumber = 26;
        temp56.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp56, 43);
        temp56.Children.Add(KeyboardGrid);
        KeyboardGrid.RowCount = 5;
        KeyboardGrid.ColumnCount = 5;
        KeyboardGrid.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        KeyboardGrid.Alignment = Fuse.Elements.Alignment.Bottom;
        KeyboardGrid.Padding = float4(0f, 10f, 0f, 10f);
        KeyboardGrid.Name = __selector12;
        KeyboardGrid.SourceLineNumber = 27;
        KeyboardGrid.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetRowSpan(KeyboardGrid, 43);
        KeyboardGrid.Children.Add(usageTextInput);
        KeyboardGrid.Children.Add(temp4);
        KeyboardGrid.Children.Add(temp62);
        KeyboardGrid.Children.Add(temp5);
        KeyboardGrid.Children.Add(temp67);
        KeyboardGrid.Children.Add(temp6);
        KeyboardGrid.Children.Add(temp69);
        KeyboardGrid.Children.Add(temp70);
        KeyboardGrid.Bindings.Add(temp72);
        usageTextInput.TextAlignment = Fuse.Controls.TextAlignment.Center;
        usageTextInput.TextColor = float4(0f, 0f, 0f, 1f);
        usageTextInput.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        usageTextInput.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        usageTextInput.Padding = float4(1f, 1f, 1f, 1f);
        usageTextInput.Name = __selector13;
        usageTextInput.SourceLineNumber = 29;
        usageTextInput.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetColumnSpan(usageTextInput, 5);
        usageTextInput.Children.Add(temp57);
        usageTextInput.Bindings.Add(temp60);
        temp57.SourceLineNumber = 30;
        temp57.SourceFileName = "InputPage.ux";
        temp57.Fills.Add(temp58);
        temp57.Strokes.Add(temp59);
        temp58.Color = float4(1f, 1f, 1f, 1f);
        temp59.Color = float4(1f, 1f, 1f, 1f);
        temp59.Width = 1f;
        temp22.SourceLineNumber = 29;
        temp22.SourceFileName = "InputPage.ux";
        temp23.SourceLineNumber = 29;
        temp23.SourceFileName = "InputPage.ux";
        temp4.SourceLineNumber = 35;
        temp4.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetColumnSpan(temp4, 3);
        global::Fuse.Gestures.Clicked.AddHandler(temp4, temp_eb10.OnEvent);
        temp4.Bindings.Add(temp61);
        temp4.Bindings.Add(temp_eb10);
        temp24.SourceLineNumber = 35;
        temp24.SourceFileName = "InputPage.ux";
        temp25.SourceLineNumber = 35;
        temp25.SourceFileName = "InputPage.ux";
        temp62.ColumnCount = 8;
        temp62.SourceLineNumber = 36;
        temp62.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetColumnSpan(temp62, 2);
        temp62.Children.Add(usage_button);
        usage_button.Text = "BOOKMARK";
        usage_button.Name = __selector14;
        usage_button.SourceLineNumber = 37;
        usage_button.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetColumnSpan(usage_button, 8);
        usage_button.Children.Add(temp63);
        temp63.SourceLineNumber = 38;
        temp63.SourceFileName = "InputPage.ux";
        temp63.Actions.Add(temp64);
        temp64.Value = true;
        temp64.SourceLineNumber = 39;
        temp64.SourceFileName = "InputPage.ux";
        temp5.SourceLineNumber = 44;
        temp5.SourceFileName = "InputPage.ux";
        temp5.Templates.Add(temp65);
        temp5.Bindings.Add(temp66);
        temp26.SourceLineNumber = 44;
        temp26.SourceFileName = "InputPage.ux";
        temp67.Text = "<";
        temp67.SourceLineNumber = 47;
        temp67.SourceFileName = "InputPage.ux";
        global::Fuse.Gestures.Clicked.AddHandler(temp67, temp_eb12.OnEvent);
        temp67.Bindings.Add(temp_eb12);
        temp27.SourceLineNumber = 47;
        temp27.SourceFileName = "InputPage.ux";
        temp6.SourceLineNumber = 48;
        temp6.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetColumnSpan(temp6, 2);
        temp6.Bindings.Add(temp68);
        temp28.SourceLineNumber = 48;
        temp28.SourceFileName = "InputPage.ux";
        temp69.Text = "PUT";
        temp69.SourceLineNumber = 49;
        temp69.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetColumnSpan(temp69, 2);
        global::Fuse.Gestures.Clicked.AddHandler(temp69, temp_eb13.OnEvent);
        temp69.Bindings.Add(temp_eb13);
        temp29.SourceLineNumber = 49;
        temp29.SourceFileName = "InputPage.ux";
        temp70.SourceLineNumber = 51;
        temp70.SourceFileName = "InputPage.ux";
        temp70.Animators.Add(temp71);
        temp71.Y = -1f;
        temp71.RelativeTo = Fuse.Triggers.WhileKeyboardVisible.Keyboard;
        temp30.SourceLineNumber = 27;
        temp30.SourceFileName = "InputPage.ux";
        temp73.Key = "FullWindow";
        temp73.SourceLineNumber = 57;
        temp73.SourceFileName = "InputPage.ux";
        temp73.Value = FullWindo;
        ModalConfirm.IsEnabled = false;
        ModalConfirm.Name = __selector15;
        ModalConfirm.SourceLineNumber = 58;
        ModalConfirm.SourceFileName = "InputPage.ux";
        ModalConfirm.Node = temp74;
        ModalConfirm.Bindings.Add(temp97);
        temp74.Color = float4(1f, 1f, 1f, 0f);
        temp74.Layer = Fuse.Layer.Overlay;
        temp74.SourceLineNumber = 59;
        temp74.SourceFileName = "InputPage.ux";
        temp74.Children.Add(temp75);
        temp75.Alignment = Fuse.Elements.Alignment.Center;
        temp75.Padding = float4(10f, 10f, 10f, 10f);
        temp75.SourceLineNumber = 60;
        temp75.SourceFileName = "InputPage.ux";
        temp75.Children.Add(temp76);
        temp75.Children.Add(temp78);
        temp75.Children.Add(temp83);
        temp75.Children.Add(temp90);
        temp76.CornerRadius = float4(10f, 10f, 10f, 10f);
        temp76.Color = float4(1f, 1f, 1f, 1f);
        temp76.Layer = Fuse.Layer.Background;
        temp76.SourceLineNumber = 61;
        temp76.SourceFileName = "InputPage.ux";
        temp76.Strokes.Add(temp7);
        temp76.Bindings.Add(temp77);
        temp7.Width = 2f;
        temp31.SourceLineNumber = 62;
        temp31.SourceFileName = "InputPage.ux";
        temp78.SourceLineNumber = 65;
        temp78.SourceFileName = "InputPage.ux";
        temp78.Children.Add(temp8);
        temp8.CornerRadius = float4(8f, 8f, 8f, 8f);
        temp8.SourceLineNumber = 66;
        temp8.SourceFileName = "InputPage.ux";
        temp8.Children.Add(temp79);
        temp8.Bindings.Add(temp82);
        temp79.ColumnCount = 8;
        temp79.SourceLineNumber = 67;
        temp79.SourceFileName = "InputPage.ux";
        temp79.Children.Add(popup_input);
        temp79.Children.Add(temp81);
        popup_input.PlaceholderText = "add your usage";
        popup_input.TextAlignment = Fuse.Controls.TextAlignment.Center;
        popup_input.TextColor = float4(0f, 0f, 0f, 1f);
        popup_input.Height = new Uno.UX.Size(30f, Uno.UX.Unit.Unspecified);
        popup_input.Name = __selector16;
        popup_input.SourceLineNumber = 68;
        popup_input.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetColumnSpan(popup_input, 6);
        popup_input.Bindings.Add(temp80);
        temp32.SourceLineNumber = 68;
        temp32.SourceFileName = "InputPage.ux";
        temp81.Text = "ADD";
        temp81.SourceLineNumber = 69;
        temp81.SourceFileName = "InputPage.ux";
        global::Fuse.Controls.Grid.SetColumnSpan(temp81, 2);
        global::Fuse.Gestures.Clicked.AddHandler(temp81, temp_eb14.OnEvent);
        temp81.Bindings.Add(temp_eb14);
        temp33.SourceLineNumber = 69;
        temp33.SourceFileName = "InputPage.ux";
        temp34.SourceLineNumber = 66;
        temp34.SourceFileName = "InputPage.ux";
        temp83.SourceLineNumber = 75;
        temp83.SourceFileName = "InputPage.ux";
        temp83.Children.Add(temp84);
        temp84.Width = new Uno.UX.Size(200f, Uno.UX.Unit.Unspecified);
        temp84.Height = new Uno.UX.Size(150f, Uno.UX.Unit.Unspecified);
        temp84.SourceLineNumber = 76;
        temp84.SourceFileName = "InputPage.ux";
        temp84.Children.Add(temp85);
        temp85.SourceLineNumber = 77;
        temp85.SourceFileName = "InputPage.ux";
        temp85.Children.Add(temp9);
        temp9.SourceLineNumber = 78;
        temp9.SourceFileName = "InputPage.ux";
        temp9.Templates.Add(temp86);
        temp9.Bindings.Add(temp87);
        temp9.Bindings.Add(temp88);
        temp9.Bindings.Add(temp89);
        temp35.SourceLineNumber = 78;
        temp35.SourceFileName = "InputPage.ux";
        temp36.SourceLineNumber = 78;
        temp36.SourceFileName = "InputPage.ux";
        temp37.SourceLineNumber = 78;
        temp37.SourceFileName = "InputPage.ux";
        temp90.SourceLineNumber = 106;
        temp90.SourceFileName = "InputPage.ux";
        temp90.Children.Add(temp91);
        temp90.Children.Add(temp92);
        temp90.Children.Add(temp94);
        temp91.Value = "OK";
        temp91.TextAlignment = Fuse.Controls.TextAlignment.Center;
        temp91.Color = float4(0f, 0f, 0f, 1f);
        temp91.Alignment = Fuse.Elements.Alignment.Center;
        temp91.SourceLineNumber = 107;
        temp91.SourceFileName = "InputPage.ux";
        temp92.CornerRadius = float4(5f, 5f, 5f, 5f);
        temp92.SourceLineNumber = 108;
        temp92.SourceFileName = "InputPage.ux";
        temp92.Strokes.Add(temp10);
        temp92.Bindings.Add(temp93);
        temp10.Width = 2f;
        temp38.SourceLineNumber = 109;
        temp38.SourceFileName = "InputPage.ux";
        temp94.SourceLineNumber = 111;
        temp94.SourceFileName = "InputPage.ux";
        temp94.Actions.Add(temp95);
        temp94.Actions.Add(temp96);
        temp95.Value = false;
        temp95.SourceLineNumber = 112;
        temp95.SourceFileName = "InputPage.ux";
        temp96.SourceLineNumber = 113;
        temp96.SourceFileName = "InputPage.ux";
        temp96.File = new global::Uno.UX.BundleFileSource(import("../../Click.wav"));
        temp39.SourceLineNumber = 58;
        temp39.SourceFileName = "InputPage.ux";
        __g_nametable.This = this;
        __g_nametable.Objects.Add(FullWindo);
        __g_nametable.Objects.Add(ScreenGrid);
        __g_nametable.Objects.Add(KeyboardGrid);
        __g_nametable.Objects.Add(usageTextInput);
        __g_nametable.Objects.Add(temp_eb10);
        __g_nametable.Objects.Add(usage_button);
        __g_nametable.Objects.Add(temp_eb12);
        __g_nametable.Objects.Add(temp_eb13);
        __g_nametable.Objects.Add(ModalConfirm);
        __g_nametable.Objects.Add(popup_input);
        __g_nametable.Objects.Add(temp_eb14);
        this.Children.Add(temp40);
        this.Children.Add(FullWindo);
        this.Children.Add(temp41);
        this.Children.Add(temp73);
        this.Children.Add(ModalConfirm);
    }
    static global::Uno.UX.Selector __selector0 = "Value";
    static global::Uno.UX.Selector __selector1 = "TextColor";
    static global::Uno.UX.Selector __selector2 = "Color";
    static global::Uno.UX.Selector __selector3 = "Opacity";
    static global::Uno.UX.Selector __selector4 = "Text";
    static global::Uno.UX.Selector __selector5 = "IsEnabled";
    static global::Uno.UX.Selector __selector6 = "Items";
    static global::Uno.UX.Selector __selector7 = "Offset";
    static global::Uno.UX.Selector __selector8 = "Limit";
    static global::Uno.UX.Selector __selector9 = "ParentNode";
    static global::Uno.UX.Selector __selector10 = "FullWindo";
    static global::Uno.UX.Selector __selector11 = "ScreenGrid";
    static global::Uno.UX.Selector __selector12 = "KeyboardGrid";
    static global::Uno.UX.Selector __selector13 = "usageTextInput";
    static global::Uno.UX.Selector __selector14 = "usage_button";
    static global::Uno.UX.Selector __selector15 = "ModalConfirm";
    static global::Uno.UX.Selector __selector16 = "popup_input";
}
