[Uno.Compiler.UxGenerated]
public partial class MainView: Fuse.App
{
    [Uno.Compiler.UxGenerated]
    public partial class Template: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly MainView __parent;
        [Uno.WeakReference] internal readonly MainView __parentInstance;
        public Template(MainView parent, MainView parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        global::Uno.UX.Property<string> aBtn_Text_inst;
        global::Uno.UX.Property<string> bTBox_Value_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> bTBox_Visibility_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> bEdit_Visibility_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> aBtn_Visibility_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> OK_Visibility_inst;
        internal global::wbButton aBtn;
        internal global::Fuse.Reactive.EventBinding temp_eb40;
        internal global::Fuse.Controls.TextBox bTBox;
        internal global::wbButton bEdit;
        internal global::wbButton OK;
        internal global::Fuse.Reactive.EventBinding temp_eb41;
        static Template()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Controls.Grid();
            var temp = new global::Fuse.Reactive.Data("SelectAccount");
            aBtn = new global::wbButton();
            aBtn_Text_inst = new AccountBook_FuseControlsButtonBase_Text_Property(aBtn, __selector0);
            var temp1 = new global::Fuse.Reactive.Data("title");
            bTBox = new global::Fuse.Controls.TextBox();
            bTBox_Value_inst = new AccountBook_FuseControlsTextInputControl_Value_Property(bTBox, __selector1);
            var temp2 = new global::Fuse.Reactive.Data("title");
            bTBox_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(bTBox, __selector2);
            bEdit = new global::wbButton();
            bEdit_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(bEdit, __selector2);
            aBtn_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(aBtn, __selector2);
            OK = new global::wbButton();
            OK_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(OK, __selector2);
            var temp3 = new global::Fuse.Reactive.Data("editTitle");
            var temp4 = new global::Fuse.Controls.DockPanel();
            var temp5 = new global::Fuse.Effects.DropShadow();
            temp_eb40 = new global::Fuse.Reactive.EventBinding(temp);
            var temp6 = new global::Fuse.Reactive.DataBinding(aBtn_Text_inst, temp1, Fuse.Reactive.BindingMode.Default);
            var temp7 = new global::Fuse.Reactive.DataBinding(bTBox_Value_inst, temp2, Fuse.Reactive.BindingMode.Default);
            var temp8 = new global::Fuse.Controls.DockPanel();
            var temp9 = new global::Fuse.Gestures.Clicked();
            var temp10 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bTBox_Visibility_inst);
            var temp11 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bEdit_Visibility_inst);
            var temp12 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aBtn_Visibility_inst);
            var temp13 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(OK_Visibility_inst);
            var temp14 = new global::Fuse.Controls.Grid();
            var temp15 = new global::Fuse.Controls.Panel();
            var temp16 = new global::Fuse.Gestures.Clicked();
            var temp17 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(OK_Visibility_inst);
            var temp18 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bTBox_Visibility_inst);
            var temp19 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bEdit_Visibility_inst);
            var temp20 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aBtn_Visibility_inst);
            temp_eb41 = new global::Fuse.Reactive.EventBinding(temp3);
            __self.ColumnCount = 10;
            __self.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
            __self.SourceLineNumber = 93;
            __self.SourceFileName = "MainView.ux";
            global::Fuse.Controls.Grid.SetRowSpan(__self, 8);
            temp4.SourceLineNumber = 94;
            temp4.SourceFileName = "MainView.ux";
            global::Fuse.Controls.Grid.SetColumnSpan(temp4, 8);
            temp4.Children.Add(aBtn);
            temp4.Children.Add(bTBox);
            aBtn.Name = __selector3;
            aBtn.SourceLineNumber = 95;
            aBtn.SourceFileName = "MainView.ux";
            global::Fuse.Gestures.Clicked.AddHandler(aBtn, temp_eb40.OnEvent);
            aBtn.Children.Add(temp5);
            aBtn.Bindings.Add(temp_eb40);
            aBtn.Bindings.Add(temp6);
            temp5.Size = 2f;
            temp5.Angle = 0f;
            temp5.Distance = 1f;
            temp5.Spread = 0.2f;
            temp5.Color = float4(0f, 0f, 0f, 0.3764706f);
            temp5.SourceLineNumber = 96;
            temp5.SourceFileName = "MainView.ux";
            temp.SourceLineNumber = 95;
            temp.SourceFileName = "MainView.ux";
            temp1.SourceLineNumber = 95;
            temp1.SourceFileName = "MainView.ux";
            bTBox.Visibility = Fuse.Elements.Visibility.Hidden;
            bTBox.Name = __selector4;
            bTBox.SourceLineNumber = 98;
            bTBox.SourceFileName = "MainView.ux";
            bTBox.Bindings.Add(temp7);
            temp2.SourceLineNumber = 98;
            temp2.SourceFileName = "MainView.ux";
            temp8.SourceLineNumber = 100;
            temp8.SourceFileName = "MainView.ux";
            global::Fuse.Controls.Grid.SetColumnSpan(temp8, 2);
            temp8.Children.Add(bEdit);
            temp8.Children.Add(temp14);
            bEdit.Text = "EDIT";
            bEdit.Name = __selector5;
            bEdit.SourceLineNumber = 101;
            bEdit.SourceFileName = "MainView.ux";
            bEdit.Children.Add(temp9);
            temp9.SourceLineNumber = 102;
            temp9.SourceFileName = "MainView.ux";
            temp9.Actions.Add(temp10);
            temp9.Actions.Add(temp11);
            temp9.Actions.Add(temp12);
            temp9.Actions.Add(temp13);
            temp10.Value = Fuse.Elements.Visibility.Visible;
            temp10.SourceLineNumber = 103;
            temp10.SourceFileName = "MainView.ux";
            temp11.Value = Fuse.Elements.Visibility.Hidden;
            temp11.SourceLineNumber = 104;
            temp11.SourceFileName = "MainView.ux";
            temp12.Value = Fuse.Elements.Visibility.Hidden;
            temp12.SourceLineNumber = 105;
            temp12.SourceFileName = "MainView.ux";
            temp13.Value = Fuse.Elements.Visibility.Visible;
            temp13.SourceLineNumber = 106;
            temp13.SourceFileName = "MainView.ux";
            temp14.RowCount = 2;
            temp14.SourceLineNumber = 109;
            temp14.SourceFileName = "MainView.ux";
            temp14.Children.Add(temp15);
            temp14.Children.Add(OK);
            temp15.SourceLineNumber = 110;
            temp15.SourceFileName = "MainView.ux";
            OK.TextCol = float4(0f, 0f, 0f, 1f);
            OK.Text = "OK";
            OK.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
            OK.Name = __selector6;
            OK.SourceLineNumber = 111;
            OK.SourceFileName = "MainView.ux";
            global::Fuse.Gestures.Clicked.AddHandler(OK, temp_eb41.OnEvent);
            OK.Children.Add(temp16);
            OK.Bindings.Add(temp_eb41);
            temp16.SourceLineNumber = 112;
            temp16.SourceFileName = "MainView.ux";
            temp16.Actions.Add(temp17);
            temp16.Actions.Add(temp18);
            temp16.Actions.Add(temp19);
            temp16.Actions.Add(temp20);
            temp17.Value = Fuse.Elements.Visibility.Visible;
            temp17.SourceLineNumber = 113;
            temp17.SourceFileName = "MainView.ux";
            temp18.Value = Fuse.Elements.Visibility.Hidden;
            temp18.SourceLineNumber = 114;
            temp18.SourceFileName = "MainView.ux";
            temp19.Value = Fuse.Elements.Visibility.Visible;
            temp19.SourceLineNumber = 115;
            temp19.SourceFileName = "MainView.ux";
            temp20.Value = Fuse.Elements.Visibility.Visible;
            temp20.SourceLineNumber = 116;
            temp20.SourceFileName = "MainView.ux";
            temp3.SourceLineNumber = 111;
            temp3.SourceFileName = "MainView.ux";
            __self.Children.Add(temp4);
            __self.Children.Add(temp8);
            return __self;
        }
        static global::Uno.UX.Selector __selector0 = "Text";
        static global::Uno.UX.Selector __selector1 = "Value";
        static global::Uno.UX.Selector __selector2 = "Visibility";
        static global::Uno.UX.Selector __selector3 = "aBtn";
        static global::Uno.UX.Selector __selector4 = "bTBox";
        static global::Uno.UX.Selector __selector5 = "bEdit";
        static global::Uno.UX.Selector __selector6 = "OK";
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template1: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly MainView __parent;
        [Uno.WeakReference] internal readonly MainView __parentInstance;
        public Template1(MainView parent, MainView parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        global::Uno.UX.Property<string> aBtn_Text_inst;
        global::Uno.UX.Property<string> bTBox_Value_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> aEdit_Visibility_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> aBtn_Visibility_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> bGrid_Visibility_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> bTBox_Visibility_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> bDel_Visibility_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> bComp_Visibility_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> cGrid_Visibility_inst;
        global::Uno.UX.Property<Fuse.Elements.Visibility> cCancel_Visibility_inst;
        internal global::wbButton aBtn;
        internal global::Fuse.Reactive.EventBinding temp_eb42;
        internal global::Fuse.Controls.TextBox bTBox;
        internal global::wbButton aEdit;
        internal global::Fuse.Controls.Grid bGrid;
        internal global::wbButton bDel;
        internal global::wbButton bComp;
        internal global::Fuse.Reactive.EventBinding temp_eb43;
        internal global::Fuse.Controls.Grid cGrid;
        internal global::wbButton cCancel;
        internal global::wbButton cDel;
        internal global::Fuse.Reactive.EventBinding temp_eb44;
        static Template1()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Controls.Grid();
            var temp = new global::Fuse.Reactive.Data("SelectAccount");
            aBtn = new global::wbButton();
            aBtn_Text_inst = new AccountBook_FuseControlsButtonBase_Text_Property(aBtn, __selector0);
            var temp1 = new global::Fuse.Reactive.Data("title");
            bTBox = new global::Fuse.Controls.TextBox();
            bTBox_Value_inst = new AccountBook_FuseControlsTextInputControl_Value_Property(bTBox, __selector1);
            var temp2 = new global::Fuse.Reactive.Data("title");
            aEdit = new global::wbButton();
            aEdit_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(aEdit, __selector2);
            aBtn_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(aBtn, __selector2);
            bGrid = new global::Fuse.Controls.Grid();
            bGrid_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(bGrid, __selector2);
            bTBox_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(bTBox, __selector2);
            bDel = new global::wbButton();
            bDel_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(bDel, __selector2);
            bComp = new global::wbButton();
            bComp_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(bComp, __selector2);
            cGrid = new global::Fuse.Controls.Grid();
            cGrid_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(cGrid, __selector2);
            cCancel = new global::wbButton();
            cCancel_Visibility_inst = new AccountBook_FuseElementsElement_Visibility_Property(cCancel, __selector2);
            var temp3 = new global::Fuse.Reactive.Data("editTitle");
            var temp4 = new global::Fuse.Reactive.Data("DeleteAccount");
            var temp5 = new global::Fuse.Controls.DockPanel();
            var temp6 = new global::Fuse.Effects.DropShadow();
            temp_eb42 = new global::Fuse.Reactive.EventBinding(temp);
            var temp7 = new global::Fuse.Reactive.DataBinding(aBtn_Text_inst, temp1, Fuse.Reactive.BindingMode.Default);
            var temp8 = new global::Fuse.Reactive.DataBinding(bTBox_Value_inst, temp2, Fuse.Reactive.BindingMode.Default);
            var temp9 = new global::Fuse.Controls.DockPanel();
            var temp10 = new global::Fuse.Effects.DropShadow();
            var temp11 = new global::Fuse.Gestures.Clicked();
            var temp12 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aEdit_Visibility_inst);
            var temp13 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aBtn_Visibility_inst);
            var temp14 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bGrid_Visibility_inst);
            var temp15 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bTBox_Visibility_inst);
            var temp16 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bDel_Visibility_inst);
            var temp17 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bComp_Visibility_inst);
            var temp18 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cGrid_Visibility_inst);
            var temp19 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cCancel_Visibility_inst);
            var temp20 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cCancel_Visibility_inst);
            var temp21 = new global::Fuse.Gestures.Clicked();
            var temp22 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aEdit_Visibility_inst);
            var temp23 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aBtn_Visibility_inst);
            var temp24 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bGrid_Visibility_inst);
            var temp25 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bTBox_Visibility_inst);
            var temp26 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bDel_Visibility_inst);
            var temp27 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bComp_Visibility_inst);
            var temp28 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cGrid_Visibility_inst);
            var temp29 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cCancel_Visibility_inst);
            var temp30 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cCancel_Visibility_inst);
            var temp31 = new global::Fuse.Gestures.Clicked();
            var temp32 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aEdit_Visibility_inst);
            var temp33 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aBtn_Visibility_inst);
            var temp34 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bGrid_Visibility_inst);
            var temp35 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bTBox_Visibility_inst);
            var temp36 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bDel_Visibility_inst);
            var temp37 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bComp_Visibility_inst);
            var temp38 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cGrid_Visibility_inst);
            var temp39 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cCancel_Visibility_inst);
            var temp40 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cCancel_Visibility_inst);
            temp_eb43 = new global::Fuse.Reactive.EventBinding(temp3);
            var temp41 = new global::Fuse.Gestures.Clicked();
            var temp42 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aEdit_Visibility_inst);
            var temp43 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aBtn_Visibility_inst);
            var temp44 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bGrid_Visibility_inst);
            var temp45 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bTBox_Visibility_inst);
            var temp46 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bDel_Visibility_inst);
            var temp47 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bComp_Visibility_inst);
            var temp48 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cGrid_Visibility_inst);
            var temp49 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cCancel_Visibility_inst);
            var temp50 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cCancel_Visibility_inst);
            cDel = new global::wbButton();
            var temp51 = new global::Fuse.Gestures.Clicked();
            var temp52 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aEdit_Visibility_inst);
            var temp53 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(aBtn_Visibility_inst);
            var temp54 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bGrid_Visibility_inst);
            var temp55 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bTBox_Visibility_inst);
            var temp56 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bDel_Visibility_inst);
            var temp57 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(bComp_Visibility_inst);
            var temp58 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cGrid_Visibility_inst);
            var temp59 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cCancel_Visibility_inst);
            var temp60 = new global::Fuse.Triggers.Actions.Set<Fuse.Elements.Visibility>(cCancel_Visibility_inst);
            temp_eb44 = new global::Fuse.Reactive.EventBinding(temp4);
            __self.ColumnCount = 10;
            __self.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
            __self.SourceLineNumber = 126;
            __self.SourceFileName = "MainView.ux";
            temp5.SourceLineNumber = 127;
            temp5.SourceFileName = "MainView.ux";
            global::Fuse.Controls.Grid.SetColumnSpan(temp5, 8);
            temp5.Children.Add(aBtn);
            temp5.Children.Add(bTBox);
            aBtn.Name = __selector3;
            aBtn.SourceLineNumber = 128;
            aBtn.SourceFileName = "MainView.ux";
            global::Fuse.Gestures.Clicked.AddHandler(aBtn, temp_eb42.OnEvent);
            aBtn.Children.Add(temp6);
            aBtn.Bindings.Add(temp_eb42);
            aBtn.Bindings.Add(temp7);
            temp6.Size = 2f;
            temp6.Angle = 0f;
            temp6.Distance = 1f;
            temp6.Spread = 0.2f;
            temp6.Color = float4(0f, 0f, 0f, 0.3764706f);
            temp6.SourceLineNumber = 129;
            temp6.SourceFileName = "MainView.ux";
            temp.SourceLineNumber = 128;
            temp.SourceFileName = "MainView.ux";
            temp1.SourceLineNumber = 128;
            temp1.SourceFileName = "MainView.ux";
            bTBox.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
            bTBox.Visibility = Fuse.Elements.Visibility.Hidden;
            bTBox.Name = __selector4;
            bTBox.SourceLineNumber = 131;
            bTBox.SourceFileName = "MainView.ux";
            bTBox.Bindings.Add(temp8);
            temp2.SourceLineNumber = 131;
            temp2.SourceFileName = "MainView.ux";
            temp9.SourceLineNumber = 134;
            temp9.SourceFileName = "MainView.ux";
            global::Fuse.Controls.Grid.SetColumnSpan(temp9, 2);
            temp9.Children.Add(aEdit);
            temp9.Children.Add(bGrid);
            temp9.Children.Add(cGrid);
            aEdit.Text = "EDIT";
            aEdit.Name = __selector5;
            aEdit.SourceLineNumber = 135;
            aEdit.SourceFileName = "MainView.ux";
            aEdit.Children.Add(temp10);
            aEdit.Children.Add(temp11);
            temp10.Size = 2f;
            temp10.Angle = 0f;
            temp10.Distance = 1f;
            temp10.Spread = 0.2f;
            temp10.Color = float4(0f, 0f, 0f, 0.3764706f);
            temp10.SourceLineNumber = 136;
            temp10.SourceFileName = "MainView.ux";
            temp11.SourceLineNumber = 137;
            temp11.SourceFileName = "MainView.ux";
            temp11.Actions.Add(temp12);
            temp11.Actions.Add(temp13);
            temp11.Actions.Add(temp14);
            temp11.Actions.Add(temp15);
            temp11.Actions.Add(temp16);
            temp11.Actions.Add(temp17);
            temp11.Actions.Add(temp18);
            temp11.Actions.Add(temp19);
            temp11.Actions.Add(temp20);
            temp12.Value = Fuse.Elements.Visibility.Hidden;
            temp12.SourceLineNumber = 138;
            temp12.SourceFileName = "MainView.ux";
            temp13.Value = Fuse.Elements.Visibility.Hidden;
            temp13.SourceLineNumber = 139;
            temp13.SourceFileName = "MainView.ux";
            temp14.Value = Fuse.Elements.Visibility.Visible;
            temp14.SourceLineNumber = 141;
            temp14.SourceFileName = "MainView.ux";
            temp15.Value = Fuse.Elements.Visibility.Visible;
            temp15.SourceLineNumber = 142;
            temp15.SourceFileName = "MainView.ux";
            temp16.Value = Fuse.Elements.Visibility.Visible;
            temp16.SourceLineNumber = 143;
            temp16.SourceFileName = "MainView.ux";
            temp17.Value = Fuse.Elements.Visibility.Visible;
            temp17.SourceLineNumber = 144;
            temp17.SourceFileName = "MainView.ux";
            temp18.Value = Fuse.Elements.Visibility.Hidden;
            temp18.SourceLineNumber = 146;
            temp18.SourceFileName = "MainView.ux";
            temp19.Value = Fuse.Elements.Visibility.Hidden;
            temp19.SourceLineNumber = 147;
            temp19.SourceFileName = "MainView.ux";
            temp20.Value = Fuse.Elements.Visibility.Hidden;
            temp20.SourceLineNumber = 148;
            temp20.SourceFileName = "MainView.ux";
            bGrid.RowCount = 2;
            bGrid.Visibility = Fuse.Elements.Visibility.Hidden;
            bGrid.Name = __selector6;
            bGrid.SourceLineNumber = 151;
            bGrid.SourceFileName = "MainView.ux";
            bGrid.Children.Add(bDel);
            bGrid.Children.Add(bComp);
            bDel.TextCol = float4(0.9333333f, 0f, 0f, 1f);
            bDel.Text = "DELETE";
            bDel.Name = __selector7;
            bDel.SourceLineNumber = 152;
            bDel.SourceFileName = "MainView.ux";
            bDel.Children.Add(temp21);
            temp21.SourceLineNumber = 153;
            temp21.SourceFileName = "MainView.ux";
            temp21.Actions.Add(temp22);
            temp21.Actions.Add(temp23);
            temp21.Actions.Add(temp24);
            temp21.Actions.Add(temp25);
            temp21.Actions.Add(temp26);
            temp21.Actions.Add(temp27);
            temp21.Actions.Add(temp28);
            temp21.Actions.Add(temp29);
            temp21.Actions.Add(temp30);
            temp22.Value = Fuse.Elements.Visibility.Hidden;
            temp22.SourceLineNumber = 154;
            temp22.SourceFileName = "MainView.ux";
            temp23.Value = Fuse.Elements.Visibility.Hidden;
            temp23.SourceLineNumber = 155;
            temp23.SourceFileName = "MainView.ux";
            temp24.Value = Fuse.Elements.Visibility.Hidden;
            temp24.SourceLineNumber = 157;
            temp24.SourceFileName = "MainView.ux";
            temp25.Value = Fuse.Elements.Visibility.Visible;
            temp25.SourceLineNumber = 158;
            temp25.SourceFileName = "MainView.ux";
            temp26.Value = Fuse.Elements.Visibility.Hidden;
            temp26.SourceLineNumber = 159;
            temp26.SourceFileName = "MainView.ux";
            temp27.Value = Fuse.Elements.Visibility.Hidden;
            temp27.SourceLineNumber = 160;
            temp27.SourceFileName = "MainView.ux";
            temp28.Value = Fuse.Elements.Visibility.Visible;
            temp28.SourceLineNumber = 162;
            temp28.SourceFileName = "MainView.ux";
            temp29.Value = Fuse.Elements.Visibility.Visible;
            temp29.SourceLineNumber = 163;
            temp29.SourceFileName = "MainView.ux";
            temp30.Value = Fuse.Elements.Visibility.Visible;
            temp30.SourceLineNumber = 164;
            temp30.SourceFileName = "MainView.ux";
            bComp.Text = "OK";
            bComp.Name = __selector8;
            bComp.SourceLineNumber = 167;
            bComp.SourceFileName = "MainView.ux";
            global::Fuse.Gestures.Clicked.AddHandler(bComp, temp_eb43.OnEvent);
            bComp.Children.Add(temp31);
            bComp.Bindings.Add(temp_eb43);
            temp31.SourceLineNumber = 168;
            temp31.SourceFileName = "MainView.ux";
            temp31.Actions.Add(temp32);
            temp31.Actions.Add(temp33);
            temp31.Actions.Add(temp34);
            temp31.Actions.Add(temp35);
            temp31.Actions.Add(temp36);
            temp31.Actions.Add(temp37);
            temp31.Actions.Add(temp38);
            temp31.Actions.Add(temp39);
            temp31.Actions.Add(temp40);
            temp32.Value = Fuse.Elements.Visibility.Visible;
            temp32.SourceLineNumber = 169;
            temp32.SourceFileName = "MainView.ux";
            temp33.Value = Fuse.Elements.Visibility.Visible;
            temp33.SourceLineNumber = 170;
            temp33.SourceFileName = "MainView.ux";
            temp34.Value = Fuse.Elements.Visibility.Hidden;
            temp34.SourceLineNumber = 172;
            temp34.SourceFileName = "MainView.ux";
            temp35.Value = Fuse.Elements.Visibility.Hidden;
            temp35.SourceLineNumber = 173;
            temp35.SourceFileName = "MainView.ux";
            temp36.Value = Fuse.Elements.Visibility.Hidden;
            temp36.SourceLineNumber = 174;
            temp36.SourceFileName = "MainView.ux";
            temp37.Value = Fuse.Elements.Visibility.Hidden;
            temp37.SourceLineNumber = 175;
            temp37.SourceFileName = "MainView.ux";
            temp38.Value = Fuse.Elements.Visibility.Hidden;
            temp38.SourceLineNumber = 177;
            temp38.SourceFileName = "MainView.ux";
            temp39.Value = Fuse.Elements.Visibility.Hidden;
            temp39.SourceLineNumber = 178;
            temp39.SourceFileName = "MainView.ux";
            temp40.Value = Fuse.Elements.Visibility.Hidden;
            temp40.SourceLineNumber = 179;
            temp40.SourceFileName = "MainView.ux";
            temp3.SourceLineNumber = 167;
            temp3.SourceFileName = "MainView.ux";
            cGrid.RowCount = 2;
            cGrid.Visibility = Fuse.Elements.Visibility.Hidden;
            cGrid.Name = __selector9;
            cGrid.SourceLineNumber = 183;
            cGrid.SourceFileName = "MainView.ux";
            cGrid.Children.Add(cCancel);
            cGrid.Children.Add(cDel);
            cCancel.Text = "CANCEL";
            cCancel.Name = __selector10;
            cCancel.SourceLineNumber = 184;
            cCancel.SourceFileName = "MainView.ux";
            cCancel.Children.Add(temp41);
            temp41.SourceLineNumber = 185;
            temp41.SourceFileName = "MainView.ux";
            temp41.Actions.Add(temp42);
            temp41.Actions.Add(temp43);
            temp41.Actions.Add(temp44);
            temp41.Actions.Add(temp45);
            temp41.Actions.Add(temp46);
            temp41.Actions.Add(temp47);
            temp41.Actions.Add(temp48);
            temp41.Actions.Add(temp49);
            temp41.Actions.Add(temp50);
            temp42.Value = Fuse.Elements.Visibility.Visible;
            temp42.SourceLineNumber = 186;
            temp42.SourceFileName = "MainView.ux";
            temp43.Value = Fuse.Elements.Visibility.Visible;
            temp43.SourceLineNumber = 187;
            temp43.SourceFileName = "MainView.ux";
            temp44.Value = Fuse.Elements.Visibility.Hidden;
            temp44.SourceLineNumber = 189;
            temp44.SourceFileName = "MainView.ux";
            temp45.Value = Fuse.Elements.Visibility.Hidden;
            temp45.SourceLineNumber = 190;
            temp45.SourceFileName = "MainView.ux";
            temp46.Value = Fuse.Elements.Visibility.Hidden;
            temp46.SourceLineNumber = 191;
            temp46.SourceFileName = "MainView.ux";
            temp47.Value = Fuse.Elements.Visibility.Hidden;
            temp47.SourceLineNumber = 192;
            temp47.SourceFileName = "MainView.ux";
            temp48.Value = Fuse.Elements.Visibility.Hidden;
            temp48.SourceLineNumber = 194;
            temp48.SourceFileName = "MainView.ux";
            temp49.Value = Fuse.Elements.Visibility.Hidden;
            temp49.SourceLineNumber = 195;
            temp49.SourceFileName = "MainView.ux";
            temp50.Value = Fuse.Elements.Visibility.Hidden;
            temp50.SourceLineNumber = 196;
            temp50.SourceFileName = "MainView.ux";
            cDel.TextCol = float4(0.9333333f, 0f, 0f, 1f);
            cDel.Text = "DELETE";
            cDel.Name = __selector11;
            cDel.SourceLineNumber = 199;
            cDel.SourceFileName = "MainView.ux";
            global::Fuse.Gestures.Clicked.AddHandler(cDel, temp_eb44.OnEvent);
            cDel.Children.Add(temp51);
            cDel.Bindings.Add(temp_eb44);
            temp51.SourceLineNumber = 200;
            temp51.SourceFileName = "MainView.ux";
            temp51.Actions.Add(temp52);
            temp51.Actions.Add(temp53);
            temp51.Actions.Add(temp54);
            temp51.Actions.Add(temp55);
            temp51.Actions.Add(temp56);
            temp51.Actions.Add(temp57);
            temp51.Actions.Add(temp58);
            temp51.Actions.Add(temp59);
            temp51.Actions.Add(temp60);
            temp52.Value = Fuse.Elements.Visibility.Visible;
            temp52.SourceLineNumber = 201;
            temp52.SourceFileName = "MainView.ux";
            temp53.Value = Fuse.Elements.Visibility.Visible;
            temp53.SourceLineNumber = 202;
            temp53.SourceFileName = "MainView.ux";
            temp54.Value = Fuse.Elements.Visibility.Hidden;
            temp54.SourceLineNumber = 204;
            temp54.SourceFileName = "MainView.ux";
            temp55.Value = Fuse.Elements.Visibility.Hidden;
            temp55.SourceLineNumber = 205;
            temp55.SourceFileName = "MainView.ux";
            temp56.Value = Fuse.Elements.Visibility.Hidden;
            temp56.SourceLineNumber = 206;
            temp56.SourceFileName = "MainView.ux";
            temp57.Value = Fuse.Elements.Visibility.Hidden;
            temp57.SourceLineNumber = 207;
            temp57.SourceFileName = "MainView.ux";
            temp58.Value = Fuse.Elements.Visibility.Hidden;
            temp58.SourceLineNumber = 209;
            temp58.SourceFileName = "MainView.ux";
            temp59.Value = Fuse.Elements.Visibility.Hidden;
            temp59.SourceLineNumber = 210;
            temp59.SourceFileName = "MainView.ux";
            temp60.Value = Fuse.Elements.Visibility.Hidden;
            temp60.SourceLineNumber = 211;
            temp60.SourceFileName = "MainView.ux";
            temp4.SourceLineNumber = 199;
            temp4.SourceFileName = "MainView.ux";
            __self.Children.Add(temp5);
            __self.Children.Add(temp9);
            return __self;
        }
        static global::Uno.UX.Selector __selector0 = "Text";
        static global::Uno.UX.Selector __selector1 = "Value";
        static global::Uno.UX.Selector __selector2 = "Visibility";
        static global::Uno.UX.Selector __selector3 = "aBtn";
        static global::Uno.UX.Selector __selector4 = "bTBox";
        static global::Uno.UX.Selector __selector5 = "aEdit";
        static global::Uno.UX.Selector __selector6 = "bGrid";
        static global::Uno.UX.Selector __selector7 = "bDel";
        static global::Uno.UX.Selector __selector8 = "bComp";
        static global::Uno.UX.Selector __selector9 = "cGrid";
        static global::Uno.UX.Selector __selector10 = "cCancel";
        static global::Uno.UX.Selector __selector11 = "cDel";
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template2: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly MainView __parent;
        [Uno.WeakReference] internal readonly MainView __parentInstance;
        public Template2(MainView parent, MainView parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        static Template2()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Triggers.LayoutAnimation();
            var temp = new global::Fuse.Animations.Move();
            __self.SourceLineNumber = 218;
            __self.SourceFileName = "MainView.ux";
            temp.Y = 1f;
            temp.Duration = 0.4;
            temp.RelativeTo = Fuse.Triggers.LayoutTransition.PositionLayoutChange;
            temp.Easing = Fuse.Animations.Easing.ElasticIn;
            __self.Animators.Add(temp);
            return __self;
        }
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template3: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly MainView __parent;
        [Uno.WeakReference] internal readonly MainView __parentInstance;
        public Template3(MainView parent, MainView parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        static Template3()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Triggers.AddingAnimation();
            var temp = new global::Fuse.Animations.Move();
            __self.SourceLineNumber = 222;
            __self.SourceFileName = "MainView.ux";
            temp.X = 1f;
            temp.Duration = 0.3;
            temp.RelativeTo = Fuse.TranslationModes.Size;
            temp.Easing = Fuse.Animations.Easing.CircularIn;
            __self.Animators.Add(temp);
            return __self;
        }
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template4: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly MainView __parent;
        [Uno.WeakReference] internal readonly MainView __parentInstance;
        public Template4(MainView parent, MainView parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        static Template4()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Triggers.RemovingAnimation();
            var temp = new global::Fuse.Animations.Move();
            __self.SourceLineNumber = 226;
            __self.SourceFileName = "MainView.ux";
            temp.X = -1f;
            temp.Duration = 0.4;
            temp.RelativeTo = Fuse.TranslationModes.Size;
            temp.Easing = Fuse.Animations.Easing.CircularOut;
            __self.Animators.Add(temp);
            return __self;
        }
    }
    global::Uno.UX.Property<float4> shadow_Color_inst;
    global::Uno.UX.Property<string> temp_Value_inst;
    global::Uno.UX.Property<object> temp1_Items_inst;
    global::Uno.UX.Property<object> temp2_Items_inst;
    global::Uno.UX.Property<float4> Hamburger_Color_inst;
    [global::Uno.UX.UXGlobalResource("SQLite")] public static readonly SQLite SQLite;
    internal global::Fuse.Controls.Grid sidebar;
    internal global::Fuse.Controls.Shadow shadow;
    internal global::Fuse.Reactive.EventBinding temp_eb45;
    internal global::Fuse.Navigation.Router router;
    internal global::Fuse.Controls.Grid Hamburger;
    internal global::Fuse.Navigation.Router router_pages;
    internal global::Fuse.Controls.PageControl pageControl;
    internal global::InputPage input;
    internal global::ListPage list;
    internal global::StatisticPage statistic;
    internal global::BudgetPage budget;
    global::Uno.UX.NameTable __g_nametable;
    static string[] __g_static_nametable = new string[] {
        "sidebar",
        "shadow",
        "temp_eb45",
        "router",
        "Hamburger",
        "router_pages",
        "pageControl",
        "input",
        "list",
        "statistic",
        "budget"
    };
    internal global::Fuse.Reactive.FuseJS.DiagnosticsImplModule FuseReactiveFuseJSDiagnosticsImplModule;
    internal global::Fuse.Reactive.FuseJS.Http FuseReactiveFuseJSHttp;
    internal global::Fuse.Reactive.FuseJS.TimerModule FuseReactiveFuseJSTimerModule;
    internal global::Fuse.Drawing.BrushConverter FuseDrawingBrushConverter;
    internal global::Fuse.Triggers.BusyTaskModule FuseTriggersBusyTaskModule;
    internal global::Fuse.Testing.UnoTestingHelper FuseTestingUnoTestingHelper;
    internal global::Fuse.FileSystem.FileSystemModule FuseFileSystemFileSystemModule;
    internal global::Fuse.Storage.StorageModule FuseStorageStorageModule;
    internal global::Fuse.WebSocket.WebSocketClientModule FuseWebSocketWebSocketClientModule;
    internal global::Polyfills.Window.WindowModule PolyfillsWindowWindowModule;
    internal global::FuseJS.Globals FuseJSGlobals;
    internal global::FuseJS.Lifecycle FuseJSLifecycle;
    internal global::FuseJS.Environment FuseJSEnvironment;
    internal global::FuseJS.Base64 FuseJSBase64;
    internal global::FuseJS.Bundle FuseJSBundle;
    internal global::FuseJS.FileReaderImpl FuseJSFileReaderImpl;
    internal global::FuseJS.UserEvents FuseJSUserEvents;
    static MainView()
    {
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Reactive.DeviceCaps.Device, "Device");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.Linear, "Linear");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.QuadraticIn, "QuadraticIn");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.QuadraticOut, "QuadraticOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.QuadraticInOut, "QuadraticInOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.CubicIn, "CubicIn");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.CubicOut, "CubicOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.CubicInOut, "CubicInOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.QuarticIn, "QuarticIn");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.QuarticOut, "QuarticOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.QuarticInOut, "QuarticInOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.QuinticIn, "QuinticIn");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.QuinticOut, "QuinticOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.QuinticInOut, "QuinticInOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.SinusoidalIn, "SinusoidalIn");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.SinusoidalOut, "SinusoidalOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.SinusoidalInOut, "SinusoidalInOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.ExponentialIn, "ExponentialIn");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.ExponentialOut, "ExponentialOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.ExponentialInOut, "ExponentialInOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.CircularIn, "CircularIn");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.CircularOut, "CircularOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.CircularInOut, "CircularInOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.ElasticIn, "ElasticIn");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.ElasticOut, "ElasticOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.ElasticInOut, "ElasticInOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.BackIn, "BackIn");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.BackOut, "BackOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.BackInOut, "BackInOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.BounceIn, "BounceIn");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.BounceOut, "BounceOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Animations.Easing.BounceInOut, "BounceInOut");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Transparent, "Transparent");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Transparent, "Transparent");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Black, "Black");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Black, "Black");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Silver, "Silver");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Silver, "Silver");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Gray, "Gray");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Gray, "Gray");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.White, "White");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.White, "White");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Maroon, "Maroon");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Maroon, "Maroon");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Red, "Red");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Red, "Red");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Purple, "Purple");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Purple, "Purple");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Fuchsia, "Fuchsia");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Fuchsia, "Fuchsia");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Green, "Green");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Green, "Green");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Lime, "Lime");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Lime, "Lime");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Olive, "Olive");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Olive, "Olive");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Yellow, "Yellow");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Yellow, "Yellow");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Navy, "Navy");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Navy, "Navy");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Blue, "Blue");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Blue, "Blue");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Teal, "Teal");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Teal, "Teal");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Colors.Aqua, "Aqua");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Drawing.Brushes.Aqua, "Aqua");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Elements.TransformOrigins.TopLeft, "TopLeft");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Elements.TransformOrigins.Center, "Center");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Elements.TransformOrigins.Anchor, "Anchor");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Elements.TransformOrigins.HorizontalBoxCenter, "HorizontalBoxCenter");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Elements.TransformOrigins.VerticalBoxCenter, "VerticalBoxCenter");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Elements.TranslationModes.TransformOriginOffset, "TransformOriginOffset");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Elements.TranslationModes.PositionOffset, "PositionOffset");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Elements.TranslationModes.SizeFactor, "SizeFactor");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Elements.TranslationModes.Size, "Size");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.TranslationModes.Size, "Size");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.Actions.GiveFocus.Singleton, "GiveFocus");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.LayoutTransition.PositionLayoutChange, "LayoutChange");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.LayoutTransition.SizeLayoutChange, "LayoutChange");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.LayoutTransition.WorldPositionChange, "WorldPositionChange");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.LayoutTransition.PositionChange, "PositionChange");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.LayoutTransition.ResizeSizeChange, "SizeChange");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.LayoutTransition.ScalingSizeChange, "SizeChange");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.WhileKeyboardVisible.Keyboard, "Keyboard");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.IScrolledLengths.Points, "Points");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.IScrolledLengths.Pixels, "Pixels");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.IScrolledLengths.ContentSize, "ContentSize");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Triggers.IScrolledLengths.ScrollViewSize, "ScrollViewSize");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Resources.MemoryPolicy.PreloadRetain, "PreloadRetain");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Resources.MemoryPolicy.UnloadUnused, "UnloadUnused");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Resources.MemoryPolicy.QuickUnload, "QuickUnload");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Resources.MemoryPolicy.UnloadInBackgroundPolicy, "UnloadInBackground");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Font.Thin, "Thin");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Font.Light, "Light");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Font.Regular, "Regular");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Font.Medium, "Medium");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Font.Bold, "Bold");
        global::Uno.UX.Resource.SetGlobalKey(global::ListPage.Bold, "Bold");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Font.ThinItalic, "ThinItalic");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Font.LightItalic, "LightItalic");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Font.Italic, "Italic");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Font.MediumItalic, "MediumItalic");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Font.BoldItalic, "BoldItalic");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.Font.PlatformDefault, "PlatformDefault");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.ScalingModes.Identity, "Identity");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.TranslationModes.Local, "Local");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.TranslationModes.ParentSize, "ParentSize");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.TranslationModes.Width, "Width");
        global::Uno.UX.Resource.SetGlobalKey(global::Fuse.TranslationModes.Height, "Height");
        global::Uno.UX.Resource.SetGlobalKey(global::ListPage.lArrow, "lArrow");
        global::Uno.UX.Resource.SetGlobalKey(global::ListPage.rArrow, "rArrow");
        global::Uno.UX.Resource.SetGlobalKey(global::MainView.SQLite, "SQLite");
        SQLite = new global::SQLite();
        global::Uno.UX.Resource.SetGlobalKey(SQLite, "SQLite");
    }
    [global::Uno.UX.UXConstructor]
    public MainView()
    {
        InitializeUX();
    }
    void InitializeUX()
    {
        FuseReactiveFuseJSDiagnosticsImplModule = new global::Fuse.Reactive.FuseJS.DiagnosticsImplModule();
        FuseReactiveFuseJSHttp = new global::Fuse.Reactive.FuseJS.Http();
        FuseReactiveFuseJSTimerModule = new global::Fuse.Reactive.FuseJS.TimerModule();
        FuseDrawingBrushConverter = new global::Fuse.Drawing.BrushConverter();
        FuseTriggersBusyTaskModule = new global::Fuse.Triggers.BusyTaskModule();
        FuseTestingUnoTestingHelper = new global::Fuse.Testing.UnoTestingHelper();
        FuseFileSystemFileSystemModule = new global::Fuse.FileSystem.FileSystemModule();
        FuseStorageStorageModule = new global::Fuse.Storage.StorageModule();
        FuseWebSocketWebSocketClientModule = new global::Fuse.WebSocket.WebSocketClientModule();
        PolyfillsWindowWindowModule = new global::Polyfills.Window.WindowModule();
        FuseJSGlobals = new global::FuseJS.Globals();
        FuseJSLifecycle = new global::FuseJS.Lifecycle();
        FuseJSEnvironment = new global::FuseJS.Environment();
        FuseJSBase64 = new global::FuseJS.Base64();
        FuseJSBundle = new global::FuseJS.Bundle();
        FuseJSFileReaderImpl = new global::FuseJS.FileReaderImpl();
        FuseJSUserEvents = new global::FuseJS.UserEvents();
        __g_nametable = new global::Uno.UX.NameTable(null, __g_static_nametable);
        var temp3 = float4(0.9568627f, 0.827451f, 0f, 1f);
        var temp4 = float4(1f, 0.9529412f, 0.6509804f, 1f);
        var temp5 = float4(1f, 0.7411765f, 0f, 1f);
        var temp6 = float4(1f, 1f, 0.9333333f, 1f);
        shadow = new global::Fuse.Controls.Shadow();
        shadow_Color_inst = new AccountBook_FuseControlsShadow_Color_Property(shadow, __selector0);
        var temp7 = "Selected : ";
        var temp8 = new global::Fuse.Reactive.Constant(temp7);
        var temp9 = new global::Fuse.Reactive.Data("currentTitle");
        var temp = new global::Fuse.Controls.Text();
        temp_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp, __selector1);
        var temp10 = new global::Fuse.Reactive.Add(temp8, temp9);
        var temp1 = new global::Fuse.Reactive.Each();
        temp1_Items_inst = new AccountBook_FuseReactiveEach_Items_Property(temp1, __selector2);
        var temp11 = new global::Fuse.Reactive.Data("tempList");
        var temp2 = new global::Fuse.Reactive.Each();
        temp2_Items_inst = new AccountBook_FuseReactiveEach_Items_Property(temp2, __selector2);
        var temp12 = new global::Fuse.Reactive.Data("tempList");
        var temp13 = new global::Fuse.Reactive.Data("tempListAdd");
        Hamburger = new global::Fuse.Controls.Grid();
        Hamburger_Color_inst = new AccountBook_FuseControlsPanel_Color_Property(Hamburger, __selector0);
        pageControl = new global::Fuse.Controls.PageControl();
        input = new global::InputPage();
        list = new global::ListPage();
        statistic = new global::StatisticPage();
        budget = new global::BudgetPage();
        var temp14 = new global::Fuse.Reactive.JavaScript(__g_nametable);
        var temp15 = new global::Uno.UX.Resource("Col_type1", temp3);
        var temp16 = new global::Uno.UX.Resource("Col_type2", temp4);
        var temp17 = new global::Uno.UX.Resource("Col_type3", temp5);
        var temp18 = new global::Uno.UX.Resource("Col_type4", temp6);
        var temp19 = new global::Fuse.Controls.EdgeNavigator();
        sidebar = new global::Fuse.Controls.Grid();
        var temp20 = new global::Fuse.Navigation.ActivatingAnimation();
        var temp21 = new global::Fuse.Animations.Change<float4>(shadow_Color_inst);
        var temp22 = new global::Fuse.Controls.Text();
        var temp23 = new global::Fuse.Reactive.DataBinding(temp_Value_inst, temp10, Fuse.Reactive.BindingMode.Default);
        var temp24 = new global::Fuse.Controls.Rectangle();
        var temp25 = new Template(this, this);
        var temp26 = new global::Fuse.Reactive.DataBinding(temp1_Items_inst, temp11, Fuse.Reactive.BindingMode.Default);
        var temp27 = new global::Fuse.Controls.ScrollView();
        var temp28 = new global::Fuse.Controls.Grid();
        var temp29 = new Template1(this, this);
        var temp30 = new Template2(this, this);
        var temp31 = new Template3(this, this);
        var temp32 = new Template4(this, this);
        var temp33 = new global::Fuse.Reactive.DataBinding(temp2_Items_inst, temp12, Fuse.Reactive.BindingMode.Default);
        var temp34 = new global::wbButton();
        temp_eb45 = new global::Fuse.Reactive.EventBinding(temp13);
        var temp35 = new global::Fuse.Drawing.StaticSolidColor(float4(1f, 1f, 1f, 1f));
        router = new global::Fuse.Navigation.Router();
        var temp36 = new global::Fuse.Controls.DockPanel();
        var temp37 = new global::Fuse.Controls.StatusBarBackground();
        var temp38 = new global::Fuse.Drawing.StaticSolidColor(float4(0.5333334f, 0.5333334f, 0.5333334f, 1f));
        var temp39 = new global::Fuse.Controls.Grid();
        var temp40 = new global::Banner();
        var temp41 = new global::Fuse.Controls.Button();
        var temp42 = new global::Fuse.Gestures.Clicked();
        var temp43 = new global::Fuse.Navigation.NavigateToggle();
        var temp44 = new global::Fuse.Controls.Rectangle();
        var temp45 = new global::Fuse.Controls.Rectangle();
        var temp46 = new global::Fuse.Controls.Rectangle();
        var temp47 = new global::Fuse.Controls.Rectangle();
        var temp48 = new global::Fuse.Controls.Rectangle();
        var temp49 = new global::Fuse.Controls.Rectangle();
        var temp50 = new global::Fuse.Controls.Rectangle();
        var temp51 = new global::Fuse.Gestures.WhilePressed();
        var temp52 = new global::Fuse.Animations.Change<float4>(Hamburger_Color_inst);
        var temp53 = new global::Fuse.Controls.Grid();
        var temp54 = new global::PageTab(pageControl, input);
        var temp55 = new global::PageTab(pageControl, list);
        var temp56 = new global::PageTab(pageControl, statistic);
        var temp57 = new global::PageTab(pageControl, budget);
        var temp58 = new global::Fuse.Controls.Page();
        router_pages = new global::Fuse.Navigation.Router();
        temp14.LineNumber = 3;
        temp14.FileName = "MainView.ux";
        temp14.SourceLineNumber = 3;
        temp14.SourceFileName = "MainView.ux";
        temp14.File = new global::Uno.UX.BundleFileSource(import("../../Modules/MainView.js"));
        temp19.SourceLineNumber = 80;
        temp19.SourceFileName = "MainView.ux";
        temp19.Children.Add(sidebar);
        temp19.Children.Add(router);
        temp19.Children.Add(temp36);
        sidebar.RowCount = 100;
        sidebar.Width = new Uno.UX.Size(80f, Uno.UX.Unit.Percent);
        sidebar.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        sidebar.Name = __selector3;
        sidebar.SourceLineNumber = 82;
        sidebar.SourceFileName = "MainView.ux";
        global::Fuse.Navigation.EdgeNavigation.SetEdge(sidebar, Fuse.Navigation.NavigationEdge.Left);
        sidebar.Background = temp35;
        sidebar.Children.Add(shadow);
        sidebar.Children.Add(temp20);
        sidebar.Children.Add(temp22);
        sidebar.Children.Add(temp);
        sidebar.Children.Add(temp24);
        sidebar.Children.Add(temp1);
        sidebar.Children.Add(temp27);
        sidebar.Children.Add(temp34);
        shadow.Angle = 180f;
        shadow.Distance = 8f;
        shadow.Size = 16f;
        shadow.Color = float4(0f, 0f, 0f, 0f);
        shadow.Name = __selector4;
        shadow.SourceLineNumber = 83;
        shadow.SourceFileName = "MainView.ux";
        temp20.SourceLineNumber = 84;
        temp20.SourceFileName = "MainView.ux";
        temp20.Animators.Add(temp21);
        temp21.Value = float4(0f, 0f, 0f, 0.2666667f);
        temp22.Value = "Book List";
        temp22.FontSize = 45f;
        temp22.Alignment = Fuse.Elements.Alignment.Center;
        temp22.SourceLineNumber = 88;
        temp22.SourceFileName = "MainView.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp22, 18);
        temp.SourceLineNumber = 89;
        temp.SourceFileName = "MainView.ux";
        temp.Bindings.Add(temp23);
        temp10.SourceLineNumber = 89;
        temp10.SourceFileName = "MainView.ux";
        temp8.SourceLineNumber = 89;
        temp8.SourceFileName = "MainView.ux";
        temp9.SourceLineNumber = 89;
        temp9.SourceFileName = "MainView.ux";
        temp24.SourceLineNumber = 90;
        temp24.SourceFileName = "MainView.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp24, 5);
        temp1.Limit = 1;
        temp1.SourceLineNumber = 92;
        temp1.SourceFileName = "MainView.ux";
        temp1.Templates.Add(temp25);
        temp1.Bindings.Add(temp26);
        temp11.SourceLineNumber = 92;
        temp11.SourceFileName = "MainView.ux";
        temp27.SourceLineNumber = 123;
        temp27.SourceFileName = "MainView.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp27, 41);
        temp27.Children.Add(temp28);
        temp28.ColumnCount = 1;
        temp28.SourceLineNumber = 124;
        temp28.SourceFileName = "MainView.ux";
        temp28.Children.Add(temp2);
        temp2.Offset = 1;
        temp2.Limit = 10000;
        temp2.SourceLineNumber = 125;
        temp2.SourceFileName = "MainView.ux";
        temp2.Templates.Add(temp29);
        temp2.Templates.Add(temp30);
        temp2.Templates.Add(temp31);
        temp2.Templates.Add(temp32);
        temp2.Bindings.Add(temp33);
        temp12.SourceLineNumber = 125;
        temp12.SourceFileName = "MainView.ux";
        temp34.Text = "ADD";
        temp34.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Unspecified);
        temp34.SourceLineNumber = 232;
        temp34.SourceFileName = "MainView.ux";
        global::Fuse.Controls.Grid.SetRow(temp34, 74);
        global::Fuse.Controls.Grid.SetRowSpan(temp34, 8);
        global::Fuse.Gestures.Clicked.AddHandler(temp34, temp_eb45.OnEvent);
        temp34.Bindings.Add(temp_eb45);
        temp13.SourceLineNumber = 232;
        temp13.SourceFileName = "MainView.ux";
        router.Name = __selector5;
        router.SourceLineNumber = 238;
        router.SourceFileName = "MainView.ux";
        temp36.SourceLineNumber = 239;
        temp36.SourceFileName = "MainView.ux";
        temp36.Children.Add(temp37);
        temp36.Children.Add(temp39);
        temp36.Children.Add(temp58);
        temp37.SourceLineNumber = 240;
        temp37.SourceFileName = "MainView.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp37, Fuse.Layouts.Dock.Top);
        temp37.Background = temp38;
        temp39.RowCount = 100;
        temp39.SourceLineNumber = 243;
        temp39.SourceFileName = "MainView.ux";
        temp39.Children.Add(temp40);
        temp39.Children.Add(temp53);
        temp40.SourceLineNumber = 245;
        temp40.SourceFileName = "MainView.ux";
        global::Fuse.Controls.Grid.SetRowSpan(temp40, 5);
        temp40.Children.Add(temp41);
        temp41.Width = new Uno.UX.Size(30f, Uno.UX.Unit.Unspecified);
        temp41.Alignment = Fuse.Elements.Alignment.Left;
        temp41.Layer = Fuse.Layer.Overlay;
        temp41.SourceLineNumber = 246;
        temp41.SourceFileName = "MainView.ux";
        temp41.Children.Add(temp42);
        temp41.Children.Add(Hamburger);
        temp41.Children.Add(temp51);
        temp42.SourceLineNumber = 248;
        temp42.SourceFileName = "MainView.ux";
        temp42.Actions.Add(temp43);
        temp43.SourceLineNumber = 249;
        temp43.SourceFileName = "MainView.ux";
        temp43.Target = sidebar;
        Hamburger.RowCount = 7;
        Hamburger.Padding = float4(4f, 4f, 4f, 4f);
        Hamburger.Name = __selector6;
        Hamburger.SourceLineNumber = 251;
        Hamburger.SourceFileName = "MainView.ux";
        Hamburger.Children.Add(temp44);
        Hamburger.Children.Add(temp45);
        Hamburger.Children.Add(temp46);
        Hamburger.Children.Add(temp47);
        Hamburger.Children.Add(temp48);
        Hamburger.Children.Add(temp49);
        Hamburger.Children.Add(temp50);
        temp44.Color = float4(1f, 0.7411765f, 0f, 1f);
        temp44.SourceLineNumber = 252;
        temp44.SourceFileName = "MainView.ux";
        temp45.CornerRadius = float4(4f, 4f, 4f, 4f);
        temp45.Color = float4(1f, 1f, 1f, 1f);
        temp45.SourceLineNumber = 253;
        temp45.SourceFileName = "MainView.ux";
        temp46.Color = float4(1f, 0.7411765f, 0f, 1f);
        temp46.SourceLineNumber = 254;
        temp46.SourceFileName = "MainView.ux";
        temp47.CornerRadius = float4(4f, 4f, 4f, 4f);
        temp47.Color = float4(1f, 1f, 1f, 1f);
        temp47.SourceLineNumber = 255;
        temp47.SourceFileName = "MainView.ux";
        temp48.Color = float4(1f, 0.7411765f, 0f, 1f);
        temp48.SourceLineNumber = 256;
        temp48.SourceFileName = "MainView.ux";
        temp49.CornerRadius = float4(4f, 4f, 4f, 4f);
        temp49.Color = float4(1f, 1f, 1f, 1f);
        temp49.SourceLineNumber = 257;
        temp49.SourceFileName = "MainView.ux";
        temp50.Color = float4(1f, 0.7411765f, 0f, 1f);
        temp50.SourceLineNumber = 258;
        temp50.SourceFileName = "MainView.ux";
        temp51.SourceLineNumber = 260;
        temp51.SourceFileName = "MainView.ux";
        temp51.Animators.Add(temp52);
        temp52.Value = float4(0.5333334f, 0.5333334f, 0.5333334f, 1f);
        temp52.Duration = 0.05;
        temp52.DurationBack = 0.2;
        temp53.ColumnCount = 4;
        temp53.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp53.SourceLineNumber = 267;
        temp53.SourceFileName = "MainView.ux";
        global::Fuse.Controls.DockPanel.SetDock(temp53, Fuse.Layouts.Dock.Top);
        global::Fuse.Controls.Grid.SetRowSpan(temp53, 8);
        temp53.Children.Add(temp54);
        temp53.Children.Add(temp55);
        temp53.Children.Add(temp56);
        temp53.Children.Add(temp57);
        temp54.Label = "INPUT";
        temp54.SourceLineNumber = 268;
        temp54.SourceFileName = "MainView.ux";
        temp55.Label = "LIST";
        temp55.SourceLineNumber = 269;
        temp55.SourceFileName = "MainView.ux";
        temp56.Label = "STATISTIC";
        temp56.SourceLineNumber = 270;
        temp56.SourceFileName = "MainView.ux";
        temp57.Label = "BUDGET";
        temp57.SourceLineNumber = 271;
        temp57.SourceFileName = "MainView.ux";
        temp58.SourceLineNumber = 278;
        temp58.SourceFileName = "MainView.ux";
        temp58.Children.Add(router_pages);
        temp58.Children.Add(pageControl);
        router_pages.Name = __selector7;
        router_pages.SourceLineNumber = 279;
        router_pages.SourceFileName = "MainView.ux";
        pageControl.Name = __selector8;
        pageControl.SourceLineNumber = 280;
        pageControl.SourceFileName = "MainView.ux";
        pageControl.Children.Add(input);
        pageControl.Children.Add(list);
        pageControl.Children.Add(statistic);
        pageControl.Children.Add(budget);
        input.Name = __selector9;
        input.SourceLineNumber = 281;
        input.SourceFileName = "MainView.ux";
        list.Name = __selector10;
        list.SourceLineNumber = 282;
        list.SourceFileName = "MainView.ux";
        statistic.Name = __selector11;
        statistic.SourceLineNumber = 283;
        statistic.SourceFileName = "MainView.ux";
        budget.Name = __selector12;
        budget.SourceLineNumber = 284;
        budget.SourceFileName = "MainView.ux";
        __g_nametable.This = this;
        __g_nametable.Objects.Add(sidebar);
        __g_nametable.Objects.Add(shadow);
        __g_nametable.Objects.Add(temp_eb45);
        __g_nametable.Objects.Add(router);
        __g_nametable.Objects.Add(Hamburger);
        __g_nametable.Objects.Add(router_pages);
        __g_nametable.Objects.Add(pageControl);
        __g_nametable.Objects.Add(input);
        __g_nametable.Objects.Add(list);
        __g_nametable.Objects.Add(statistic);
        __g_nametable.Objects.Add(budget);
        this.Children.Add(temp14);
        this.Children.Add(temp19);
        this.Resources.Add(temp15);
        this.Resources.Add(temp16);
        this.Resources.Add(temp17);
        this.Resources.Add(temp18);
    }
    static global::Uno.UX.Selector __selector0 = "Color";
    static global::Uno.UX.Selector __selector1 = "Value";
    static global::Uno.UX.Selector __selector2 = "Items";
    static global::Uno.UX.Selector __selector3 = "sidebar";
    static global::Uno.UX.Selector __selector4 = "shadow";
    static global::Uno.UX.Selector __selector5 = "router";
    static global::Uno.UX.Selector __selector6 = "Hamburger";
    static global::Uno.UX.Selector __selector7 = "router_pages";
    static global::Uno.UX.Selector __selector8 = "pageControl";
    static global::Uno.UX.Selector __selector9 = "input";
    static global::Uno.UX.Selector __selector10 = "list";
    static global::Uno.UX.Selector __selector11 = "statistic";
    static global::Uno.UX.Selector __selector12 = "budget";
}
