[Uno.Compiler.UxGenerated]
public partial class StatisticPage: Fuse.Controls.Panel
{
    readonly Fuse.Navigation.Router router;
    [Uno.Compiler.UxGenerated]
    public partial class Template: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly StatisticPage __parent;
        [Uno.WeakReference] internal readonly StatisticPage __parentInstance;
        public Template(StatisticPage parent, StatisticPage parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        global::Uno.UX.Property<string> __self_Value_inst;
        static Template()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Controls.Text();
            __self_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(__self, __selector0);
            var temp = new global::Fuse.Reactive.Data("");
            var temp1 = new global::Fuse.Reactive.DataBinding(__self_Value_inst, temp, Fuse.Reactive.BindingMode.Default);
            __self.Alignment = Fuse.Elements.Alignment.Center;
            __self.Bindings.Add(temp1);
            return __self;
        }
        static global::Uno.UX.Selector __selector0 = "Value";
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template1: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly StatisticPage __parent;
        [Uno.WeakReference] internal readonly StatisticPage __parentInstance;
        public Template1(StatisticPage parent, StatisticPage parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        global::Uno.UX.Property<string> __self_text_inst;
        internal global::Fuse.Reactive.EventBinding temp_eb57;
        static Template1()
        {
        }
        public override object New()
        {
            var __self = new global::myButton();
            __self_text_inst = new AccountBook_myButton_text_Property(__self, __selector0);
            var temp = new global::Fuse.Reactive.Data("value");
            var temp1 = new global::Fuse.Reactive.Data("Click_calendar_number");
            var temp2 = new global::Fuse.Controls.Rectangle();
            var temp3 = new global::Fuse.Reactive.DataBinding(__self_text_inst, temp, Fuse.Reactive.BindingMode.Default);
            temp_eb57 = new global::Fuse.Reactive.EventBinding(temp1);
            __self.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
            __self.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
            __self.textcolor = Fuse.Drawing.Colors.Black;
            __self.fontsize = 15;
            global::Fuse.Gestures.Clicked.AddHandler(__self, temp_eb57.OnEvent);
            temp2.CornerRadius = float4(5f, 5f, 5f, 5f);
            temp2.Color = Fuse.Drawing.Colors.White;
            __self.font = global::ListPage.Bold;
            __self.Children.Add(temp2);
            __self.Bindings.Add(temp3);
            __self.Bindings.Add(temp_eb57);
            return __self;
        }
        static global::Uno.UX.Selector __selector0 = "text";
    }
    [Uno.Compiler.UxGenerated]
    public partial class Template2: Uno.UX.Template
    {
        [Uno.WeakReference] internal readonly StatisticPage __parent;
        [Uno.WeakReference] internal readonly StatisticPage __parentInstance;
        public Template2(StatisticPage parent, StatisticPage parentInstance): base(null, false)
        {
            __parent = parent;
            __parentInstance = parentInstance;
        }
        global::Uno.UX.Property<string> temp_Text_inst;
        internal global::Fuse.Reactive.EventBinding temp_eb59;
        static Template2()
        {
        }
        public override object New()
        {
            var __self = new global::Fuse.Controls.ScrollView();
            var temp1 = new global::Fuse.Reactive.Data("SelectUsage");
            var temp = new global::wbButton_Left();
            temp_Text_inst = new AccountBook_FuseControlsButtonBase_Text_Property(temp, __selector0);
            var temp2 = new global::Fuse.Reactive.Data("name");
            var temp3 = new global::Fuse.Gestures.Clicked();
            var temp4 = new global::Fuse.PlaySound();
            temp_eb59 = new global::Fuse.Reactive.EventBinding(temp1);
            var temp5 = new global::Fuse.Reactive.DataBinding(temp_Text_inst, temp2, Fuse.Reactive.BindingMode.Default);
            __self.AllowedScrollDirections = Fuse.Controls.ScrollDirections.Horizontal;
            global::Fuse.Gestures.Clicked.AddHandler(temp, temp_eb59.OnEvent);
            temp.Children.Add(temp3);
            temp.Bindings.Add(temp_eb59);
            temp.Bindings.Add(temp5);
            temp3.Actions.Add(temp4);
            temp4.File = new global::Uno.UX.BundleFileSource(import("../../../Click.wav"));
            __self.Children.Add(temp);
            return __self;
        }
        static global::Uno.UX.Selector __selector0 = "Text";
    }
    global::Uno.UX.Property<bool> ModalConfirm_IsEnabled_inst;
    global::Uno.UX.Property<string> temp_text_inst;
    global::Uno.UX.Property<string> temp1_Value_inst;
    global::Uno.UX.Property<string> temp2_Value_inst;
    global::Uno.UX.Property<string> temp3_text_inst;
    global::Uno.UX.Property<string> temp4_text_inst;
    global::Uno.UX.Property<string> temp5_Value_inst;
    global::Uno.UX.Property<string> temp6_Value_inst;
    global::Uno.UX.Property<string> temp7_text_inst;
    global::Uno.UX.Property<string> temp8_text_inst;
    global::Uno.UX.Property<bool> ModalConfirm2_IsEnabled_inst;
    global::Uno.UX.Property<string> temp9_Value_inst;
    global::Uno.UX.Property<string> temp10_Value_inst;
    global::Uno.UX.Property<string> temp11_Value_inst;
    global::Uno.UX.Property<float4> temp12_Color_inst;
    global::Uno.UX.Property<float4> calendar_lbutton_Color_inst;
    global::Uno.UX.Property<string> temp13_Value_inst;
    global::Uno.UX.Property<float4> calendar_rbutton_Color_inst;
    global::Uno.UX.Property<object> temp14_Items_inst;
    global::Uno.UX.Property<object> temp15_Items_inst;
    global::Uno.UX.Property<float4> temp16_Color_inst;
    global::Uno.UX.Property<Fuse.Visual> ModalConfirm_ParentNode_inst;
    global::Uno.UX.Property<float4> temp17_Color_inst;
    global::Uno.UX.Property<string> temp18_Value_inst;
    global::Uno.UX.Property<object> temp19_Items_inst;
    global::Uno.UX.Property<int> temp19_Offset_inst;
    global::Uno.UX.Property<int> temp19_Limit_inst;
    global::Uno.UX.Property<float4> temp20_Color_inst;
    global::Uno.UX.Property<Fuse.Visual> ModalConfirm2_ParentNode_inst;
    internal global::Fuse.Controls.Panel FullWindo;
    internal global::Fuse.Controls.Panel FullWindo2;
    internal global::Fuse.Reactive.EventBinding temp_eb50;
    internal global::Fuse.Reactive.EventBinding temp_eb51;
    internal global::Fuse.Reactive.EventBinding temp_eb52;
    internal global::Fuse.Reactive.EventBinding temp_eb53;
    internal global::Fuse.Reactive.EventBinding temp_eb54;
    internal global::Fuse.AlternateRoot ModalConfirm;
    internal global::Fuse.Controls.Image calendar_lbutton;
    internal global::Fuse.Reactive.EventBinding temp_eb55;
    internal global::Fuse.Controls.Image calendar_rbutton;
    internal global::Fuse.Reactive.EventBinding temp_eb56;
    internal global::Fuse.Reactive.EventBinding temp_eb58;
    internal global::Fuse.AlternateRoot ModalConfirm2;
    internal global::Fuse.Reactive.EventBinding temp_eb60;
    global::Uno.UX.NameTable __g_nametable;
    static string[] __g_static_nametable = new string[] {
        "router",
        "FullWindo",
        "FullWindo2",
        "temp_eb50",
        "temp_eb51",
        "temp_eb52",
        "temp_eb53",
        "temp_eb54",
        "ModalConfirm",
        "calendar_lbutton",
        "temp_eb55",
        "calendar_rbutton",
        "temp_eb56",
        "temp_eb58",
        "ModalConfirm2",
        "temp_eb60"
    };
    static StatisticPage()
    {
    }
    [global::Uno.UX.UXConstructor]
    public StatisticPage(
		[global::Uno.UX.UXParameter("router")] Fuse.Navigation.Router router)
    {
        this.router = router;
        InitializeUX();
    }
    void InitializeUX()
    {
        __g_nametable = new global::Uno.UX.NameTable(null, __g_static_nametable);
        ModalConfirm = new global::Fuse.AlternateRoot();
        ModalConfirm_IsEnabled_inst = new AccountBook_FuseAlternateRoot_IsEnabled_Property(ModalConfirm, __selector0);
        var temp21 = new global::Fuse.Reactive.Data("Click_spcf_total_date");
        var temp = new global::myButton();
        temp_text_inst = new AccountBook_myButton_text_Property(temp, __selector1);
        var temp22 = new global::Fuse.Reactive.Data("screen_spcf_datetime_string");
        var temp1 = new global::Fuse.Controls.Text();
        temp1_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp1, __selector2);
        var temp23 = new global::Fuse.Reactive.Data("spcf_input_total");
        var temp2 = new global::Fuse.Controls.Text();
        temp2_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp2, __selector2);
        var temp24 = new global::Fuse.Reactive.Data("spcf_output_total");
        var temp25 = new global::Fuse.Reactive.Data("Click_intv_tot_date_left");
        var temp3 = new global::myButton();
        temp3_text_inst = new AccountBook_myButton_text_Property(temp3, __selector1);
        var temp26 = new global::Fuse.Reactive.Data("screen_intv_tot_datetime_left_string");
        var temp27 = new global::Fuse.Reactive.Data("Click_intv_tot_date_right");
        var temp4 = new global::myButton();
        temp4_text_inst = new AccountBook_myButton_text_Property(temp4, __selector1);
        var temp28 = new global::Fuse.Reactive.Data("screen_intv_tot_datetime_right_string");
        var temp5 = new global::Fuse.Controls.Text();
        temp5_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp5, __selector2);
        var temp29 = new global::Fuse.Reactive.Data("intv_tot_input_total");
        var temp6 = new global::Fuse.Controls.Text();
        temp6_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp6, __selector2);
        var temp30 = new global::Fuse.Reactive.Data("intv_tot_output_total");
        var temp31 = new global::Fuse.Reactive.Data("Click_item_tot_date_left");
        var temp7 = new global::myButton();
        temp7_text_inst = new AccountBook_myButton_text_Property(temp7, __selector1);
        var temp32 = new global::Fuse.Reactive.Data("screen_item_tot_datetime_left_string");
        var temp33 = new global::Fuse.Reactive.Data("Click_item_tot_date_right");
        var temp8 = new global::myButton();
        temp8_text_inst = new AccountBook_myButton_text_Property(temp8, __selector1);
        var temp34 = new global::Fuse.Reactive.Data("screen_item_tot_datetime_right_string");
        ModalConfirm2 = new global::Fuse.AlternateRoot();
        ModalConfirm2_IsEnabled_inst = new AccountBook_FuseAlternateRoot_IsEnabled_Property(ModalConfirm2, __selector0);
        var temp9 = new global::Fuse.Controls.Text();
        temp9_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp9, __selector2);
        var temp35 = new global::Fuse.Reactive.Data("selected_item");
        var temp10 = new global::Fuse.Controls.Text();
        temp10_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp10, __selector2);
        var temp36 = new global::Fuse.Reactive.Data("item_tot_input_total");
        var temp11 = new global::Fuse.Controls.Text();
        temp11_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp11, __selector2);
        var temp37 = new global::Fuse.Reactive.Data("item_tot_output_total");
        var temp12 = new global::Fuse.Drawing.Stroke();
        temp12_Color_inst = new AccountBook_FuseDrawingStroke_Color_Property(temp12, __selector3);
        var temp38 = new global::Fuse.Reactive.Resource("Col_type3");
        calendar_lbutton = new global::Fuse.Controls.Image();
        calendar_lbutton_Color_inst = new AccountBook_FuseControlsImage_Color_Property(calendar_lbutton, __selector3);
        var temp39 = new global::Fuse.Reactive.Data("Click_calendar_lArrow");
        var temp13 = new global::Fuse.Controls.Text();
        temp13_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp13, __selector2);
        var temp40 = new global::Fuse.Reactive.Data("calendarDateTime");
        calendar_rbutton = new global::Fuse.Controls.Image();
        calendar_rbutton_Color_inst = new AccountBook_FuseControlsImage_Color_Property(calendar_rbutton, __selector3);
        var temp41 = new global::Fuse.Reactive.Data("Click_calendar_rArrow");
        var temp14 = new global::Fuse.Reactive.Each();
        temp14_Items_inst = new AccountBook_FuseReactiveEach_Items_Property(temp14, __selector4);
        var temp42 = new global::Fuse.Reactive.Data("dayNameMatrix");
        var temp15 = new global::Fuse.Reactive.Each();
        temp15_Items_inst = new AccountBook_FuseReactiveEach_Items_Property(temp15, __selector4);
        var temp43 = new global::Fuse.Reactive.Data("calendarMatrix");
        var temp16 = new global::Fuse.Drawing.Stroke();
        temp16_Color_inst = new AccountBook_FuseDrawingStroke_Color_Property(temp16, __selector3);
        var temp44 = new global::Fuse.Reactive.Resource("Col_type3");
        var temp45 = new global::Fuse.Reactive.Data("Ok_click");
        ModalConfirm_ParentNode_inst = new AccountBook_FuseAlternateRoot_ParentNode_Property(ModalConfirm, __selector5);
        var temp46 = new global::Fuse.Reactive.Resource("FullWindow");
        var temp17 = new global::Fuse.Drawing.Stroke();
        temp17_Color_inst = new AccountBook_FuseDrawingStroke_Color_Property(temp17, __selector3);
        var temp47 = new global::Fuse.Reactive.Resource("Col_type3");
        var temp18 = new global::Fuse.Controls.Text();
        temp18_Value_inst = new AccountBook_FuseControlsTextControl_Value_Property(temp18, __selector2);
        var temp48 = new global::Fuse.Reactive.Data("selected_item");
        var temp19 = new global::Fuse.Reactive.Each();
        temp19_Items_inst = new AccountBook_FuseReactiveEach_Items_Property(temp19, __selector4);
        var temp49 = new global::Fuse.Reactive.Data("tempUsageList");
        temp19_Offset_inst = new AccountBook_FuseReactiveEach_Offset_Property(temp19, __selector6);
        var temp50 = new global::Fuse.Reactive.Data("offset");
        temp19_Limit_inst = new AccountBook_FuseReactiveEach_Limit_Property(temp19, __selector7);
        var temp51 = new global::Fuse.Reactive.Data("limit");
        var temp20 = new global::Fuse.Drawing.Stroke();
        temp20_Color_inst = new AccountBook_FuseDrawingStroke_Color_Property(temp20, __selector3);
        var temp52 = new global::Fuse.Reactive.Resource("Col_type3");
        var temp53 = new global::Fuse.Reactive.Data("CalculateIntervalItemTotal");
        ModalConfirm2_ParentNode_inst = new AccountBook_FuseAlternateRoot_ParentNode_Property(ModalConfirm2, __selector5);
        var temp54 = new global::Fuse.Reactive.Resource("FullWindow2");
        FullWindo = new global::Fuse.Controls.Panel();
        FullWindo2 = new global::Fuse.Controls.Panel();
        var temp55 = new global::Fuse.Reactive.JavaScript(__g_nametable);
        var temp56 = new global::Fuse.Controls.Grid();
        var temp57 = new global::Fuse.Controls.Rectangle();
        var temp58 = new global::Fuse.Controls.ScrollView();
        var temp59 = new global::Fuse.Controls.StackPanel();
        var temp60 = new global::Fuse.Controls.Text();
        var temp61 = new global::Fuse.Controls.StackPanel();
        var temp62 = new global::Fuse.Gestures.Clicked();
        var temp63 = new global::Fuse.Triggers.Actions.Set<bool>(ModalConfirm_IsEnabled_inst);
        temp_eb50 = new global::Fuse.Reactive.EventBinding(temp21);
        var temp64 = new global::Fuse.Reactive.DataBinding(temp_text_inst, temp22, Fuse.Reactive.BindingMode.Default);
        var temp65 = new global::Fuse.Controls.Rectangle();
        var temp66 = new global::Fuse.Controls.Grid();
        var temp67 = new global::Fuse.Controls.Text();
        var temp68 = new global::Fuse.Reactive.DataBinding(temp1_Value_inst, temp23, Fuse.Reactive.BindingMode.Default);
        var temp69 = new global::Fuse.Controls.Text();
        var temp70 = new global::Fuse.Reactive.DataBinding(temp2_Value_inst, temp24, Fuse.Reactive.BindingMode.Default);
        var temp71 = new global::Fuse.Controls.Text();
        var temp72 = new global::Fuse.Controls.StackPanel();
        var temp73 = new global::Fuse.Gestures.Clicked();
        var temp74 = new global::Fuse.Triggers.Actions.Set<bool>(ModalConfirm_IsEnabled_inst);
        temp_eb51 = new global::Fuse.Reactive.EventBinding(temp25);
        var temp75 = new global::Fuse.Reactive.DataBinding(temp3_text_inst, temp26, Fuse.Reactive.BindingMode.Default);
        var temp76 = new global::Fuse.Controls.Text();
        var temp77 = new global::Fuse.Gestures.Clicked();
        var temp78 = new global::Fuse.Triggers.Actions.Set<bool>(ModalConfirm_IsEnabled_inst);
        temp_eb52 = new global::Fuse.Reactive.EventBinding(temp27);
        var temp79 = new global::Fuse.Reactive.DataBinding(temp4_text_inst, temp28, Fuse.Reactive.BindingMode.Default);
        var temp80 = new global::Fuse.Controls.Rectangle();
        var temp81 = new global::Fuse.Controls.Grid();
        var temp82 = new global::Fuse.Controls.Text();
        var temp83 = new global::Fuse.Reactive.DataBinding(temp5_Value_inst, temp29, Fuse.Reactive.BindingMode.Default);
        var temp84 = new global::Fuse.Controls.Text();
        var temp85 = new global::Fuse.Reactive.DataBinding(temp6_Value_inst, temp30, Fuse.Reactive.BindingMode.Default);
        var temp86 = new global::Fuse.Controls.Text();
        var temp87 = new global::Fuse.Controls.StackPanel();
        var temp88 = new global::Fuse.Gestures.Clicked();
        var temp89 = new global::Fuse.Triggers.Actions.Set<bool>(ModalConfirm_IsEnabled_inst);
        temp_eb53 = new global::Fuse.Reactive.EventBinding(temp31);
        var temp90 = new global::Fuse.Reactive.DataBinding(temp7_text_inst, temp32, Fuse.Reactive.BindingMode.Default);
        var temp91 = new global::Fuse.Controls.Text();
        var temp92 = new global::Fuse.Gestures.Clicked();
        var temp93 = new global::Fuse.Triggers.Actions.Set<bool>(ModalConfirm_IsEnabled_inst);
        temp_eb54 = new global::Fuse.Reactive.EventBinding(temp33);
        var temp94 = new global::Fuse.Reactive.DataBinding(temp8_text_inst, temp34, Fuse.Reactive.BindingMode.Default);
        var temp95 = new global::Fuse.Controls.Rectangle();
        var temp96 = new global::Fuse.Controls.Grid();
        var temp97 = new global::Fuse.Controls.Button();
        var temp98 = new global::Fuse.Gestures.Clicked();
        var temp99 = new global::Fuse.Triggers.Actions.Set<bool>(ModalConfirm2_IsEnabled_inst);
        var temp100 = new global::Fuse.PlaySound();
        var temp101 = new global::Fuse.Reactive.DataBinding(temp9_Value_inst, temp35, Fuse.Reactive.BindingMode.Default);
        var temp102 = new global::Fuse.Controls.Text();
        var temp103 = new global::Fuse.Reactive.DataBinding(temp10_Value_inst, temp36, Fuse.Reactive.BindingMode.Default);
        var temp104 = new global::Fuse.Controls.Text();
        var temp105 = new global::Fuse.Reactive.DataBinding(temp11_Value_inst, temp37, Fuse.Reactive.BindingMode.Default);
        var temp106 = new global::Fuse.Controls.Rectangle();
        var temp107 = new global::Fuse.Drawing.StaticSolidColor(float4(1f, 0.7411765f, 0f, 1f));
        var temp108 = new global::Fuse.Resources.ResourceObject();
        var temp109 = new global::Fuse.Resources.ResourceObject();
        var temp110 = new global::Fuse.Controls.Panel();
        var temp111 = new global::Fuse.Controls.StackPanel();
        var temp112 = new global::Fuse.Controls.Rectangle();
        var temp113 = new global::Fuse.Reactive.DataBinding(temp12_Color_inst, temp38, Fuse.Reactive.BindingMode.Default);
        var temp114 = new global::Fuse.Controls.StackPanel();
        var temp115 = new global::ccButton();
        var temp116 = new global::Fuse.Gestures.WhilePressed();
        var temp117 = new global::Fuse.Animations.Change<float4>(calendar_lbutton_Color_inst);
        var temp118 = new global::Fuse.Effects.DropShadow();
        temp_eb55 = new global::Fuse.Reactive.EventBinding(temp39);
        var temp119 = new global::Fuse.Reactive.DataBinding(temp13_Value_inst, temp40, Fuse.Reactive.BindingMode.Default);
        var temp120 = new global::ccButton();
        var temp121 = new global::Fuse.Gestures.WhilePressed();
        var temp122 = new global::Fuse.Animations.Change<float4>(calendar_rbutton_Color_inst);
        var temp123 = new global::Fuse.Effects.DropShadow();
        temp_eb56 = new global::Fuse.Reactive.EventBinding(temp41);
        var temp124 = new global::Fuse.Controls.Grid();
        var temp125 = new Template(this, this);
        var temp126 = new global::Fuse.Reactive.DataBinding(temp14_Items_inst, temp42, Fuse.Reactive.BindingMode.Default);
        var temp127 = new Template1(this, this);
        var temp128 = new global::Fuse.Reactive.DataBinding(temp15_Items_inst, temp43, Fuse.Reactive.BindingMode.Default);
        var temp129 = new global::Fuse.Controls.Button();
        var temp130 = new global::Fuse.Controls.Text();
        var temp131 = new global::Fuse.Controls.Rectangle();
        var temp132 = new global::Fuse.Reactive.DataBinding(temp16_Color_inst, temp44, Fuse.Reactive.BindingMode.Default);
        var temp133 = new global::Fuse.Gestures.Clicked();
        var temp134 = new global::Fuse.Triggers.Actions.Set<bool>(ModalConfirm_IsEnabled_inst);
        var temp135 = new global::Fuse.PlaySound();
        temp_eb58 = new global::Fuse.Reactive.EventBinding(temp45);
        var temp136 = new global::Fuse.Reactive.DataBinding(ModalConfirm_ParentNode_inst, temp46, Fuse.Reactive.BindingMode.Default);
        var temp137 = new global::Fuse.Controls.Panel();
        var temp138 = new global::Fuse.Controls.StackPanel();
        var temp139 = new global::Fuse.Controls.Rectangle();
        var temp140 = new global::Fuse.Reactive.DataBinding(temp17_Color_inst, temp47, Fuse.Reactive.BindingMode.Default);
        var temp141 = new global::Fuse.Controls.ScrollView();
        var temp142 = new global::Fuse.Controls.StackPanel();
        var temp143 = new global::Fuse.Reactive.DataBinding(temp18_Value_inst, temp48, Fuse.Reactive.BindingMode.Default);
        var temp144 = new Template2(this, this);
        var temp145 = new global::Fuse.Reactive.DataBinding(temp19_Items_inst, temp49, Fuse.Reactive.BindingMode.Default);
        var temp146 = new global::Fuse.Reactive.DataBinding(temp19_Offset_inst, temp50, Fuse.Reactive.BindingMode.Default);
        var temp147 = new global::Fuse.Reactive.DataBinding(temp19_Limit_inst, temp51, Fuse.Reactive.BindingMode.Default);
        var temp148 = new global::Fuse.Controls.Button();
        var temp149 = new global::Fuse.Controls.Text();
        var temp150 = new global::Fuse.Controls.Rectangle();
        var temp151 = new global::Fuse.Reactive.DataBinding(temp20_Color_inst, temp52, Fuse.Reactive.BindingMode.Default);
        var temp152 = new global::Fuse.Gestures.Clicked();
        var temp153 = new global::Fuse.Triggers.Actions.Set<bool>(ModalConfirm2_IsEnabled_inst);
        var temp154 = new global::Fuse.PlaySound();
        temp_eb60 = new global::Fuse.Reactive.EventBinding(temp53);
        var temp155 = new global::Fuse.Reactive.DataBinding(ModalConfirm2_ParentNode_inst, temp54, Fuse.Reactive.BindingMode.Default);
        FullWindo.Layer = Fuse.Layer.Overlay;
        FullWindo.Name = __selector8;
        FullWindo2.Layer = Fuse.Layer.Overlay;
        FullWindo2.Name = __selector9;
        temp55.LineNumber = 5;
        temp55.FileName = "StatisticPage.ux";
        temp55.File = new global::Uno.UX.BundleFileSource(import("../../../Modules/StatisticPage.js"));
        temp56.RowCount = 100;
        temp56.Children.Add(temp57);
        temp56.Children.Add(temp58);
        global::Fuse.Controls.Grid.SetRowSpan(temp57, 14);
        global::Fuse.Controls.Grid.SetRowSpan(temp58, 86);
        temp58.Children.Add(temp59);
        temp59.Background = temp107;
        temp59.Children.Add(temp60);
        temp59.Children.Add(temp61);
        temp59.Children.Add(temp65);
        temp59.Children.Add(temp71);
        temp59.Children.Add(temp72);
        temp59.Children.Add(temp80);
        temp59.Children.Add(temp86);
        temp59.Children.Add(temp87);
        temp59.Children.Add(temp95);
        temp59.Children.Add(temp106);
        temp60.Value = "SPECIFIC DATE TOTAL";
        temp60.FontSize = 15f;
        temp60.Color = Fuse.Drawing.Colors.White;
        temp60.Alignment = Fuse.Elements.Alignment.Center;
        temp60.Margin = float4(5f, 5f, 5f, 5f);
        temp60.Font = global::ListPage.Bold;
        temp61.Orientation = Fuse.Layouts.Orientation.Horizontal;
        temp61.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp61.Height = new Uno.UX.Size(22f, Uno.UX.Unit.Unspecified);
        temp61.Alignment = Fuse.Elements.Alignment.Center;
        temp61.Children.Add(temp);
        temp.Margin = float4(5f, 0f, 5f, 0f);
        temp.textcolor = Fuse.Drawing.Colors.White;
        temp.fontsize = 15;
        global::Fuse.Gestures.Clicked.AddHandler(temp, temp_eb50.OnEvent);
        temp.font = global::ListPage.Bold;
        temp.Children.Add(temp62);
        temp.Bindings.Add(temp_eb50);
        temp.Bindings.Add(temp64);
        temp62.Actions.Add(temp63);
        temp63.Value = true;
        temp65.CornerRadius = float4(5f, 5f, 5f, 5f);
        temp65.Color = Fuse.Drawing.Colors.White;
        temp65.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp65.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Percent);
        temp65.Margin = float4(50f, 0f, 50f, 20f);
        temp65.Children.Add(temp66);
        temp66.RowCount = 2;
        temp66.ColumnCount = 3;
        temp66.Children.Add(temp67);
        temp66.Children.Add(temp1);
        temp66.Children.Add(temp69);
        temp66.Children.Add(temp2);
        temp67.Value = "Input";
        temp67.FontSize = 15f;
        temp67.Alignment = Fuse.Elements.Alignment.Center;
        temp67.Margin = float4(0f, 5f, 0f, 5f);
        temp67.Font = global::ListPage.Bold;
        temp1.FontSize = 17f;
        temp1.Color = float4(0f, 0.4f, 0f, 1f);
        temp1.Alignment = Fuse.Elements.Alignment.Center;
        temp1.Margin = float4(0f, 5f, 0f, 5f);
        global::Fuse.Controls.Grid.SetColumnSpan(temp1, 2);
        temp1.Bindings.Add(temp68);
        temp69.Value = "Output";
        temp69.FontSize = 15f;
        temp69.Alignment = Fuse.Elements.Alignment.Center;
        temp69.Margin = float4(0f, 5f, 0f, 5f);
        temp69.Font = global::ListPage.Bold;
        temp2.FontSize = 17f;
        temp2.Color = float4(0.9333333f, 0f, 0f, 1f);
        temp2.Alignment = Fuse.Elements.Alignment.Center;
        temp2.Margin = float4(0f, 5f, 0f, 5f);
        global::Fuse.Controls.Grid.SetColumnSpan(temp2, 2);
        temp2.Bindings.Add(temp70);
        temp71.Value = "INTERVAL DATE TOTAL";
        temp71.FontSize = 15f;
        temp71.Color = Fuse.Drawing.Colors.White;
        temp71.Alignment = Fuse.Elements.Alignment.Center;
        temp71.Margin = float4(5f, 5f, 5f, 5f);
        temp71.Font = global::ListPage.Bold;
        temp72.Orientation = Fuse.Layouts.Orientation.Horizontal;
        temp72.Alignment = Fuse.Elements.Alignment.Center;
        temp72.Children.Add(temp3);
        temp72.Children.Add(temp76);
        temp72.Children.Add(temp4);
        temp3.textcolor = Fuse.Drawing.Colors.White;
        temp3.fontsize = 15;
        global::Fuse.Gestures.Clicked.AddHandler(temp3, temp_eb51.OnEvent);
        temp3.font = global::ListPage.Bold;
        temp3.Children.Add(temp73);
        temp3.Bindings.Add(temp_eb51);
        temp3.Bindings.Add(temp75);
        temp73.Actions.Add(temp74);
        temp74.Value = true;
        temp76.Value = "~";
        temp76.FontSize = 15f;
        temp76.Color = Fuse.Drawing.Colors.White;
        temp76.Margin = float4(5f, 5f, 5f, 5f);
        temp76.Font = global::ListPage.Bold;
        temp4.textcolor = Fuse.Drawing.Colors.White;
        temp4.fontsize = 15;
        global::Fuse.Gestures.Clicked.AddHandler(temp4, temp_eb52.OnEvent);
        temp4.font = global::ListPage.Bold;
        temp4.Children.Add(temp77);
        temp4.Bindings.Add(temp_eb52);
        temp4.Bindings.Add(temp79);
        temp77.Actions.Add(temp78);
        temp78.Value = true;
        temp80.CornerRadius = float4(5f, 5f, 5f, 5f);
        temp80.Color = Fuse.Drawing.Colors.White;
        temp80.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp80.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Percent);
        temp80.Margin = float4(50f, 0f, 50f, 20f);
        temp80.Children.Add(temp81);
        temp81.RowCount = 2;
        temp81.ColumnCount = 3;
        temp81.Children.Add(temp82);
        temp81.Children.Add(temp5);
        temp81.Children.Add(temp84);
        temp81.Children.Add(temp6);
        temp82.Value = "Input";
        temp82.FontSize = 15f;
        temp82.Alignment = Fuse.Elements.Alignment.Center;
        temp82.Margin = float4(0f, 5f, 0f, 5f);
        temp82.Font = global::ListPage.Bold;
        temp5.FontSize = 17f;
        temp5.Color = float4(0f, 0.4f, 0f, 1f);
        temp5.Alignment = Fuse.Elements.Alignment.Center;
        temp5.Margin = float4(0f, 5f, 0f, 5f);
        global::Fuse.Controls.Grid.SetColumnSpan(temp5, 2);
        temp5.Bindings.Add(temp83);
        temp84.Value = "Output";
        temp84.FontSize = 15f;
        temp84.Alignment = Fuse.Elements.Alignment.Center;
        temp84.Margin = float4(0f, 5f, 0f, 5f);
        temp84.Font = global::ListPage.Bold;
        temp6.FontSize = 17f;
        temp6.Color = float4(0.9333333f, 0f, 0f, 1f);
        temp6.Alignment = Fuse.Elements.Alignment.Center;
        temp6.Margin = float4(0f, 5f, 0f, 5f);
        global::Fuse.Controls.Grid.SetColumnSpan(temp6, 2);
        temp6.Bindings.Add(temp85);
        temp86.Value = "ITEM TOTAL";
        temp86.FontSize = 15f;
        temp86.Color = Fuse.Drawing.Colors.White;
        temp86.Alignment = Fuse.Elements.Alignment.Center;
        temp86.Margin = float4(5f, 5f, 5f, 5f);
        temp86.Font = global::ListPage.Bold;
        temp87.Orientation = Fuse.Layouts.Orientation.Horizontal;
        temp87.Alignment = Fuse.Elements.Alignment.Center;
        temp87.Children.Add(temp7);
        temp87.Children.Add(temp91);
        temp87.Children.Add(temp8);
        temp7.textcolor = Fuse.Drawing.Colors.White;
        temp7.fontsize = 15;
        global::Fuse.Gestures.Clicked.AddHandler(temp7, temp_eb53.OnEvent);
        temp7.font = global::ListPage.Bold;
        temp7.Children.Add(temp88);
        temp7.Bindings.Add(temp_eb53);
        temp7.Bindings.Add(temp90);
        temp88.Actions.Add(temp89);
        temp89.Value = true;
        temp91.Value = "~";
        temp91.FontSize = 15f;
        temp91.Color = Fuse.Drawing.Colors.White;
        temp91.Margin = float4(5f, 5f, 5f, 5f);
        temp91.Font = global::ListPage.Bold;
        temp8.textcolor = Fuse.Drawing.Colors.White;
        temp8.fontsize = 15;
        global::Fuse.Gestures.Clicked.AddHandler(temp8, temp_eb54.OnEvent);
        temp8.font = global::ListPage.Bold;
        temp8.Children.Add(temp92);
        temp8.Bindings.Add(temp_eb54);
        temp8.Bindings.Add(temp94);
        temp92.Actions.Add(temp93);
        temp93.Value = true;
        temp95.CornerRadius = float4(5f, 5f, 5f, 5f);
        temp95.Color = Fuse.Drawing.Colors.White;
        temp95.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp95.Height = new Uno.UX.Size(50f, Uno.UX.Unit.Percent);
        temp95.Margin = float4(50f, 0f, 50f, 20f);
        temp95.Children.Add(temp96);
        temp96.RowCount = 3;
        temp96.ColumnCount = 3;
        temp96.Children.Add(temp97);
        temp96.Children.Add(temp102);
        temp96.Children.Add(temp10);
        temp96.Children.Add(temp104);
        temp96.Children.Add(temp11);
        temp97.Width = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp97.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        temp97.Alignment = Fuse.Elements.Alignment.Center;
        temp97.Margin = float4(0f, 5f, 0f, 5f);
        global::Fuse.Controls.Grid.SetColumnSpan(temp97, 3);
        temp97.Children.Add(temp98);
        temp97.Children.Add(temp9);
        temp98.Actions.Add(temp99);
        temp98.Actions.Add(temp100);
        temp99.Value = true;
        temp100.File = new global::Uno.UX.BundleFileSource(import("../../../Click.wav"));
        temp9.FontSize = 15f;
        temp9.Alignment = Fuse.Elements.Alignment.Center;
        temp9.Font = global::ListPage.Bold;
        temp9.Bindings.Add(temp101);
        temp102.Value = "Input";
        temp102.FontSize = 15f;
        temp102.Alignment = Fuse.Elements.Alignment.Center;
        temp102.Margin = float4(0f, 5f, 0f, 5f);
        temp102.Font = global::ListPage.Bold;
        temp10.FontSize = 17f;
        temp10.Color = float4(0f, 0.4f, 0f, 1f);
        temp10.Alignment = Fuse.Elements.Alignment.Center;
        temp10.Margin = float4(0f, 5f, 0f, 5f);
        global::Fuse.Controls.Grid.SetColumnSpan(temp10, 2);
        temp10.Bindings.Add(temp103);
        temp104.Value = "Output";
        temp104.FontSize = 15f;
        temp104.Alignment = Fuse.Elements.Alignment.Center;
        temp104.Margin = float4(0f, 5f, 0f, 5f);
        temp104.Font = global::ListPage.Bold;
        temp11.FontSize = 17f;
        temp11.Color = float4(0.9333333f, 0f, 0f, 1f);
        temp11.Alignment = Fuse.Elements.Alignment.Center;
        temp11.Margin = float4(0f, 5f, 0f, 5f);
        global::Fuse.Controls.Grid.SetColumnSpan(temp11, 2);
        temp11.Bindings.Add(temp105);
        temp106.Color = float4(1f, 0.7411765f, 0f, 1f);
        temp106.Height = new Uno.UX.Size(200f, Uno.UX.Unit.Unspecified);
        temp108.Key = "FullWindow";
        temp108.Value = FullWindo;
        temp109.Key = "FullWindow2";
        temp109.Value = FullWindo2;
        ModalConfirm.IsEnabled = false;
        ModalConfirm.Name = __selector10;
        ModalConfirm.Node = temp110;
        ModalConfirm.Bindings.Add(temp136);
        temp110.Color = float4(1f, 1f, 1f, 0f);
        temp110.Layer = Fuse.Layer.Overlay;
        temp110.Children.Add(temp111);
        temp111.Alignment = Fuse.Elements.Alignment.Center;
        temp111.Padding = float4(10f, 10f, 10f, 10f);
        temp111.Children.Add(temp112);
        temp111.Children.Add(temp114);
        temp111.Children.Add(temp124);
        temp111.Children.Add(temp129);
        temp112.CornerRadius = float4(10f, 10f, 10f, 10f);
        temp112.Color = float4(1f, 1f, 1f, 1f);
        temp112.Width = new Uno.UX.Size(250f, Uno.UX.Unit.Unspecified);
        temp112.Height = new Uno.UX.Size(300f, Uno.UX.Unit.Unspecified);
        temp112.Layer = Fuse.Layer.Background;
        temp112.Strokes.Add(temp12);
        temp112.Bindings.Add(temp113);
        temp12.Width = 2f;
        temp114.Orientation = Fuse.Layouts.Orientation.Horizontal;
        temp114.Height = new Uno.UX.Size(20f, Uno.UX.Unit.Unspecified);
        temp114.Alignment = Fuse.Elements.Alignment.Center;
        temp114.Children.Add(temp115);
        temp114.Children.Add(temp13);
        temp114.Children.Add(temp120);
        temp115.Alignment = Fuse.Elements.Alignment.Center;
        temp115.Margin = float4(2f, 0f, 2f, 0f);
        global::Fuse.Gestures.Clicked.AddHandler(temp115, temp_eb55.OnEvent);
        temp115.Children.Add(calendar_lbutton);
        temp115.Children.Add(temp116);
        temp115.Children.Add(temp118);
        temp115.Bindings.Add(temp_eb55);
        calendar_lbutton.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        calendar_lbutton.Name = __selector11;
        calendar_lbutton.File = new global::Uno.UX.BundleFileSource(import("../../../images/lArrow.png"));
        temp116.Animators.Add(temp117);
        temp117.Value = float4(0.6f, 0.6f, 0.6f, 1f);
        temp117.Duration = 0.05;
        temp117.DurationBack = 0.2;
        temp118.Distance = 0.02f;
        temp118.Color = Fuse.Drawing.Colors.Black;
        temp13.Alignment = Fuse.Elements.Alignment.Center;
        temp13.Bindings.Add(temp119);
        temp120.Alignment = Fuse.Elements.Alignment.Center;
        temp120.Margin = float4(2f, 0f, 2f, 0f);
        global::Fuse.Gestures.Clicked.AddHandler(temp120, temp_eb56.OnEvent);
        temp120.Children.Add(calendar_rbutton);
        temp120.Children.Add(temp121);
        temp120.Children.Add(temp123);
        temp120.Bindings.Add(temp_eb56);
        calendar_rbutton.Height = new Uno.UX.Size(100f, Uno.UX.Unit.Percent);
        calendar_rbutton.Name = __selector12;
        calendar_rbutton.File = new global::Uno.UX.BundleFileSource(import("../../../images/rArrow.png"));
        temp121.Animators.Add(temp122);
        temp122.Value = float4(0.6f, 0.6f, 0.6f, 1f);
        temp122.Duration = 0.05;
        temp122.DurationBack = 0.2;
        temp123.Distance = 0.02f;
        temp123.Color = Fuse.Drawing.Colors.Black;
        temp124.RowCount = 7;
        temp124.ColumnCount = 7;
        temp124.Width = new Uno.UX.Size(220f, Uno.UX.Unit.Unspecified);
        temp124.Height = new Uno.UX.Size(200f, Uno.UX.Unit.Unspecified);
        temp124.Children.Add(temp14);
        temp124.Children.Add(temp15);
        temp14.Templates.Add(temp125);
        temp14.Bindings.Add(temp126);
        temp15.Templates.Add(temp127);
        temp15.Bindings.Add(temp128);
        global::Fuse.Gestures.Clicked.AddHandler(temp129, temp_eb58.OnEvent);
        temp129.Children.Add(temp130);
        temp129.Children.Add(temp131);
        temp129.Children.Add(temp133);
        temp129.Bindings.Add(temp_eb58);
        temp130.Value = "OK";
        temp130.TextAlignment = Fuse.Controls.TextAlignment.Center;
        temp130.Color = float4(0f, 0f, 0f, 1f);
        temp130.Alignment = Fuse.Elements.Alignment.Center;
        temp131.CornerRadius = float4(5f, 5f, 5f, 5f);
        temp131.Strokes.Add(temp16);
        temp131.Bindings.Add(temp132);
        temp16.Width = 2f;
        temp133.Actions.Add(temp134);
        temp133.Actions.Add(temp135);
        temp134.Value = false;
        temp135.File = new global::Uno.UX.BundleFileSource(import("../../../Click.wav"));
        ModalConfirm2.IsEnabled = false;
        ModalConfirm2.Name = __selector13;
        ModalConfirm2.Node = temp137;
        ModalConfirm2.Bindings.Add(temp155);
        temp137.Color = float4(1f, 1f, 1f, 0f);
        temp137.Layer = Fuse.Layer.Overlay;
        temp137.Children.Add(temp138);
        temp138.Alignment = Fuse.Elements.Alignment.Center;
        temp138.Padding = float4(10f, 10f, 10f, 10f);
        temp138.Children.Add(temp139);
        temp138.Children.Add(temp141);
        temp138.Children.Add(temp148);
        temp139.CornerRadius = float4(10f, 10f, 10f, 10f);
        temp139.Color = float4(1f, 1f, 1f, 1f);
        temp139.Layer = Fuse.Layer.Background;
        temp139.Strokes.Add(temp17);
        temp139.Bindings.Add(temp140);
        temp17.Width = 2f;
        temp141.Width = new Uno.UX.Size(200f, Uno.UX.Unit.Unspecified);
        temp141.Height = new Uno.UX.Size(200f, Uno.UX.Unit.Unspecified);
        temp141.Children.Add(temp142);
        temp142.Children.Add(temp18);
        temp142.Children.Add(temp19);
        temp18.Bindings.Add(temp143);
        temp19.Templates.Add(temp144);
        temp19.Bindings.Add(temp145);
        temp19.Bindings.Add(temp146);
        temp19.Bindings.Add(temp147);
        global::Fuse.Gestures.Clicked.AddHandler(temp148, temp_eb60.OnEvent);
        temp148.Children.Add(temp149);
        temp148.Children.Add(temp150);
        temp148.Children.Add(temp152);
        temp148.Bindings.Add(temp_eb60);
        temp149.Value = "OK";
        temp149.TextAlignment = Fuse.Controls.TextAlignment.Center;
        temp149.Color = float4(0f, 0f, 0f, 1f);
        temp149.Alignment = Fuse.Elements.Alignment.Center;
        temp150.CornerRadius = float4(5f, 5f, 5f, 5f);
        temp150.Strokes.Add(temp20);
        temp150.Bindings.Add(temp151);
        temp20.Width = 2f;
        temp152.Actions.Add(temp153);
        temp152.Actions.Add(temp154);
        temp153.Value = false;
        temp154.File = new global::Uno.UX.BundleFileSource(import("../../../Click.wav"));
        __g_nametable.This = this;
        __g_nametable.Objects.Add(router);
        __g_nametable.Objects.Add(FullWindo);
        __g_nametable.Objects.Add(FullWindo2);
        __g_nametable.Objects.Add(temp_eb50);
        __g_nametable.Objects.Add(temp_eb51);
        __g_nametable.Objects.Add(temp_eb52);
        __g_nametable.Objects.Add(temp_eb53);
        __g_nametable.Objects.Add(temp_eb54);
        __g_nametable.Objects.Add(ModalConfirm);
        __g_nametable.Objects.Add(calendar_lbutton);
        __g_nametable.Objects.Add(temp_eb55);
        __g_nametable.Objects.Add(calendar_rbutton);
        __g_nametable.Objects.Add(temp_eb56);
        __g_nametable.Objects.Add(temp_eb58);
        __g_nametable.Objects.Add(ModalConfirm2);
        __g_nametable.Objects.Add(temp_eb60);
        this.Children.Add(FullWindo);
        this.Children.Add(FullWindo2);
        this.Children.Add(temp55);
        this.Children.Add(temp56);
        this.Children.Add(temp108);
        this.Children.Add(temp109);
        this.Children.Add(ModalConfirm);
        this.Children.Add(ModalConfirm2);
    }
    static global::Uno.UX.Selector __selector0 = "IsEnabled";
    static global::Uno.UX.Selector __selector1 = "text";
    static global::Uno.UX.Selector __selector2 = "Value";
    static global::Uno.UX.Selector __selector3 = "Color";
    static global::Uno.UX.Selector __selector4 = "Items";
    static global::Uno.UX.Selector __selector5 = "ParentNode";
    static global::Uno.UX.Selector __selector6 = "Offset";
    static global::Uno.UX.Selector __selector7 = "Limit";
    static global::Uno.UX.Selector __selector8 = "FullWindo";
    static global::Uno.UX.Selector __selector9 = "FullWindo2";
    static global::Uno.UX.Selector __selector10 = "ModalConfirm";
    static global::Uno.UX.Selector __selector11 = "calendar_lbutton";
    static global::Uno.UX.Selector __selector12 = "calendar_rbutton";
    static global::Uno.UX.Selector __selector13 = "ModalConfirm2";
}
